# Generated by Django 6.0 on 2025-12-07 00:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('on_hold', 'On Hold'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('consultation_count', models.IntegerField(default=0)),
                ('total_fees_deducted', models.BigIntegerField(default=0)),
                ('payout_method', models.CharField(max_length=50)),
                ('payout_details', models.JSONField(blank=True, default=dict)),
                ('on_hold_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('released_from_hold_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_financial_chats', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_chats', to=settings.AUTH_USER_MODEL)),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='core.transaction')),
            ],
            options={
                'db_table': 'financial_chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('support', 'Support Message'), ('system', 'System Message')], max_length=20)),
                ('content', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='payments.financialchat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField(blank=True, null=True)),
                ('prescription_id', models.UUIDField(blank=True, null=True)),
                ('health_record_id', models.UUIDField(blank=True, null=True)),
                ('service_description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_transactions', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_health_transactions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_transaction', to='core.transaction')),
            ],
            options={
                'db_table': 'health_transactions',
            },
        ),
        migrations.CreateModel(
            name='LinkedVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_type', models.CharField(choices=[('payment_gateway', 'Payment Gateway'), ('bank', 'Bank Account'), ('mobile_money', 'Mobile Money'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card')], max_length=30)),
                ('vendor_name', models.CharField(max_length=100)),
                ('account_identifier', models.CharField(max_length=255)),
                ('encrypted_credentials', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending_verification', 'Pending Verification'), ('suspended', 'Suspended')], default='active', max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'linked_vendors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='core.transaction')),
            ],
            options={
                'db_table': 'payment_receipts',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_request', to='core.transaction')),
            ],
            options={
                'db_table': 'payment_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('on_hold', 'On Hold'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('transaction_count', models.IntegerField(default=0)),
                ('total_fees_deducted', models.BigIntegerField(default=0)),
                ('payout_method', models.CharField(max_length=50)),
                ('payout_details', models.JSONField(blank=True, default=dict)),
                ('on_hold_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('released_from_hold_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('fee', models.BigIntegerField(default=0)),
                ('total_amount', models.BigIntegerField()),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('transfer_type', models.CharField(choices=[('internal', 'Internal Transfer'), ('external', 'External Transfer'), ('bank', 'Bank Transfer'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('external_account_details', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='core.wallet')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='core.wallet')),
            ],
            options={
                'db_table': 'transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('related_transaction_id', models.UUIDField()),
                ('provider_role', models.CharField(max_length=50)),
                ('service_amount', models.BigIntegerField()),
                ('fee_amount', models.BigIntegerField()),
                ('fee_percentage', models.FloatField()),
                ('status', models.CharField(choices=[('UNCOLLECTED', 'Uncollected'), ('COLLECTED', 'Collected'), ('WAIVED', 'Waived'), ('DISPUTED', 'Disputed')], default='UNCOLLECTED', max_length=20)),
                ('payment_method', models.CharField(choices=[('WALLET', 'Wallet'), ('CASH', 'Cash'), ('EXTERNAL_GATEWAY', 'External Gateway')], max_length=30)),
                ('collection_method', models.CharField(blank=True, max_length=50)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fee_ledgers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status'], name='fee_ledgers_provide_8a9459_idx'), models.Index(fields=['related_transaction_id'], name='fee_ledgers_related_05fd01_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='financialchat',
            index=models.Index(fields=['participant', 'status'], name='financial_c_partici_e77d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='financialchat',
            index=models.Index(fields=['status'], name='financial_c_status_255b50_idx'),
        ),
        migrations.AddIndex(
            model_name='financialchatmessage',
            index=models.Index(fields=['chat', 'created_at'], name='financial_c_chat_id_1bf817_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedvendor',
            index=models.Index(fields=['participant', 'status'], name='linked_vend_partici_75b6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedvendor',
            index=models.Index(fields=['vendor_type'], name='linked_vend_vendor__0ab5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['to_user', 'status'], name='payment_req_to_user_974bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['from_user', 'status'], name='payment_req_from_us_6082f7_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['from_user', 'status'], name='transfers_from_us_b85efe_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['to_user', 'status'], name='transfers_to_user_161698_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['transfer_type'], name='transfers_transfe_fe46e4_idx'),
        ),
    ]
