# Generated by Django 6.0 on 2025-12-08 18:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FedaPayCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fedapay_customer_id', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fedapay_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fedapay_customers',
            },
        ),
        migrations.CreateModel(
            name='FedaPayPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fedapay_payout_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('fedapay_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mode', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_transferred', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('last_error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('fedapay_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='payments.fedapaycustomer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fedapay_payouts', to=settings.AUTH_USER_MODEL)),
                ('provider_payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fedapay_payouts', to='payments.providerpayout')),
            ],
            options={
                'db_table': 'fedapay_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FedaPayTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fedapay_transaction_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('fedapay_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('wallet_topup', 'Wallet Top-up'), ('service_payment', 'Service Payment'), ('refund', 'Refund'), ('payout', 'Payout')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('declined', 'Declined'), ('refunded', 'Refunded'), ('transferred', 'Transferred')], default='pending', max_length=20)),
                ('description', models.TextField()),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_token', models.CharField(blank=True, max_length=500)),
                ('payment_url', models.URLField(blank=True)),
                ('callback_url', models.URLField(blank=True)),
                ('receipt_url', models.URLField(blank=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_transferred', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('custom_metadata', models.JSONField(blank=True, default=dict)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('last_error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('core_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fedapay_transaction', to='core.transaction')),
                ('fedapay_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.fedapaycustomer')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fedapay_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fedapay_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FedaPayWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('fedapay_payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.fedapaypayout')),
                ('fedapay_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.fedapaytransaction')),
            ],
            options={
                'db_table': 'fedapay_webhook_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fedapaycustomer',
            index=models.Index(fields=['fedapay_customer_id'], name='fedapay_cus_fedapay_569796_idx'),
        ),
        migrations.AddIndex(
            model_name='fedapaycustomer',
            index=models.Index(fields=['participant'], name='fedapay_cus_partici_8076fc_idx'),
        ),
        migrations.AddIndex(
            model_name='fedapaypayout',
            index=models.Index(fields=['provider', 'status'], name='fedapay_pay_provide_89582f_idx'),
        ),
        migrations.AddIndex(
            model_name='fedapaypayout',
            index=models.Index(fields=['fedapay_payout_id'], name='fedapay_pay_fedapay_3c672f_idx'),
        ),
        migrations.AddIndex(
            model_name='fedapaypayout',
            index=models.Index(fields=['status'], name='fedapay_pay_status_8118d2_idx'),
        ),
        migrations.AddIndex(
            model_name='fedapaytransaction',
            index=models.Index(fields=['participant', 'status'], name='fedapay_tra_partici_b703c1_idx'),
        ),
        migrations.AddIndex(
            model_name='fedapaytransaction',
            index=models.Index(fields=['fedapay_transaction_id'], name='fedapay_tra_fedapay_09f3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='fedapaytransaction',
            index=models.Index(fields=['fedapay_reference'], name='fedapay_tra_fedapay_d59ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='fedapaytransaction',
            index=models.Index(fields=['transaction_type'], name='fedapay_tra_transac_88bf0b_idx'),
        ),
        migrations.AddIndex(
            model_name='fedapaytransaction',
            index=models.Index(fields=['status'], name='fedapay_tra_status_7a3b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='fedapaywebhookevent',
            index=models.Index(fields=['event_type', 'processed'], name='fedapay_web_event_t_e8c73c_idx'),
        ),
        migrations.AddIndex(
            model_name='fedapaywebhookevent',
            index=models.Index(fields=['created_at'], name='fedapay_web_created_7d1c46_idx'),
        ),
    ]
