# Generated by Django 6.0 on 2025-12-10 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_transportprovider_transport_p_status_84f75f_idx_and_more'),
        ('payments', '0002_fedapaycustomer_fedapaypayout_fedapaytransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='payment_method',
            field=models.CharField(blank=True, default='cash', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='qr_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='service_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='transaction_type',
            field=models.CharField(choices=[('APPOINTMENT', 'Appointment Payment'), ('PRESCRIPTION', 'Prescription Purchase'), ('CONSULTATION', 'Consultation Fee'), ('WALLET_DEPOSIT', 'Wallet Deposit'), ('WALLET_WITHDRAWAL', 'Wallet Withdrawal'), ('INSURANCE_CLAIM', 'Insurance Claim'), ('TRANSPORT', 'Transport Service'), ('PHARMACY', 'Pharmacy Purchase'), ('HOSPITAL_SERVICE', 'Hospital Service'), ('LAB_TEST', 'Laboratory Test'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['issued_to', '-issued_at'], name='payment_rec_issued__9e9888_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['transaction_type', '-issued_at'], name='payment_rec_transac_97b16f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['receipt_number'], name='payment_rec_receipt_5b8ffe_idx'),
        ),
    ]
