# Generated by Django 6.0 on 2025-12-13 08:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentreceipt_amount_paymentreceipt_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='E.164 format, e.g., +22997000000', max_length=20)),
                ('country_code', models.CharField(help_text='ISO country code, e.g., BJ, TG, CI', max_length=2)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('verification_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(choices=[('sms', 'SMS'), ('call', 'Call'), ('whatsapp', 'WhatsApp')], default='sms', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_for_payment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_phones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participant_phones',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantGatewayAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_role', models.CharField(max_length=50)),
                ('gateway_provider', models.CharField(choices=[('fedapay', 'FedaPay'), ('mtn_momo', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('orange_money', 'Orange Money')], max_length=50)),
                ('gateway_customer_id', models.CharField(blank=True, max_length=255)),
                ('gateway_account_number', models.CharField(max_length=255)),
                ('payout_mode', models.CharField(blank=True, help_text='For FedaPay: mtn, moov, mtn_ci, moov_tg, etc.', max_length=50)),
                ('account_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_accounts', to=settings.AUTH_USER_MODEL)),
                ('participant_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_accounts', to='payments.participantphone')),
            ],
            options={
                'db_table': 'participant_gateway_accounts',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GatewayTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_provider', models.CharField(choices=[('fedapay', 'FedaPay'), ('mtn_momo', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('orange_money', 'Orange Money')], max_length=50)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255)),
                ('gateway_reference', models.CharField(blank=True, max_length=255)),
                ('transaction_type', models.CharField(choices=[('payment_collection', 'Payment Collection'), ('payout', 'Payout'), ('refund', 'Refund')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('refunded', 'Refunded'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('payment_url', models.URLField(blank=True)),
                ('payment_token', models.CharField(blank=True, max_length=500)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_transferred', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('webhook_data', models.JSONField(blank=True, default=list, help_text='Array of webhook payloads')),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('last_error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_gateway_transactions', to=settings.AUTH_USER_MODEL)),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_gateway_transactions', to=settings.AUTH_USER_MODEL)),
                ('patient_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_gateway_transactions', to='payments.participantphone')),
                ('provider_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_gateway_transactions', to='payments.participantphone')),
            ],
            options={
                'db_table': 'gateway_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_role', models.CharField(max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_transactions_count', models.IntegerField(default=0)),
                ('total_gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fees_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payout_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gateway_payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_schedules', to='payments.gatewaytransaction')),
                ('participant', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'hospital', 'pharmacy', 'insurance_company']}, on_delete=django.db.models.deletion.CASCADE, related_name='payout_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payout_schedules',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_provider_role', models.CharField(max_length=50)),
                ('service_category', models.CharField(choices=[('consultation', 'Consultation'), ('surgery', 'Surgery'), ('diagnostic', 'Diagnostic'), ('laboratory', 'Laboratory'), ('imaging', 'Imaging'), ('therapy', 'Therapy'), ('pharmacy', 'Pharmacy'), ('emergency', 'Emergency'), ('vaccination', 'Vaccination'), ('dental', 'Dental'), ('maternity', 'Maternity'), ('pediatric', 'Pediatric'), ('insurance_plan', 'Insurance Plan'), ('other', 'Other')], max_length=50)),
                ('service_name', models.CharField(max_length=255)),
                ('service_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Estimated duration', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('requires_appointment', models.BooleanField(default=True)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL)),
                ('service_provider', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'hospital', 'pharmacy', 'insurance_company']}, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_catalog',
                'ordering': ['service_category', 'service_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_ref', models.CharField(max_length=100, unique=True)),
                ('service_provider_role', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('appointment', 'Appointment'), ('prescription', 'Prescription'), ('lab_test', 'Lab Test'), ('consultation', 'Consultation'), ('pharmacy_purchase', 'Pharmacy Purchase'), ('insurance_claim', 'Insurance Claim'), ('emergency', 'Emergency Service'), ('other', 'Other')], max_length=50)),
                ('service_id', models.UUIDField(help_text='Reference to specific service instance')),
                ('service_description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('payment_method', models.CharField(choices=[('fedapay_mobile', 'FedaPay Mobile Money'), ('fedapay_card', 'FedaPay Card'), ('mtn_momo', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('orange_money', 'Orange Money'), ('onsite_cash', 'On-site Cash')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_transactions', to='payments.gatewaytransaction')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_service_transactions', to=settings.AUTH_USER_MODEL)),
                ('patient_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transactions', to='payments.participantphone')),
                ('provider_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_transactions', to='payments.participantphone')),
                ('service_catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.servicecatalog')),
                ('service_provider', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'hospital', 'pharmacy', 'insurance_company']}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_service_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee_rate', models.DecimalField(decimal_places=4, default=0.01, max_digits=5)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.18, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount_to_provider', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_collected', models.BooleanField(default=False)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_details', to='payments.servicetransaction')),
            ],
            options={
                'db_table': 'transaction_fees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='participantphone',
            index=models.Index(fields=['participant', 'is_primary'], name='participant_partici_d5ca53_idx'),
        ),
        migrations.AddIndex(
            model_name='participantphone',
            index=models.Index(fields=['phone_number'], name='participant_phone_n_9e83e9_idx'),
        ),
        migrations.AddIndex(
            model_name='participantphone',
            index=models.Index(fields=['is_verified'], name='participant_is_veri_c0e6b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participantphone',
            unique_together={('participant', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='participantgatewayaccount',
            index=models.Index(fields=['participant', 'gateway_provider'], name='participant_partici_49ba62_idx'),
        ),
        migrations.AddIndex(
            model_name='participantgatewayaccount',
            index=models.Index(fields=['gateway_provider', 'gateway_customer_id'], name='participant_gateway_15f5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='participantgatewayaccount',
            index=models.Index(fields=['participant', 'is_default'], name='participant_partici_a093c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participantgatewayaccount',
            unique_together={('participant', 'gateway_provider', 'gateway_account_number')},
        ),
        migrations.AddIndex(
            model_name='gatewaytransaction',
            index=models.Index(fields=['gateway_provider', 'gateway_transaction_id'], name='gateway_tra_gateway_7ef0ec_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewaytransaction',
            index=models.Index(fields=['gateway_reference'], name='gateway_tra_gateway_ba2e63_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewaytransaction',
            index=models.Index(fields=['patient', 'status'], name='gateway_tra_patient_378db6_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewaytransaction',
            index=models.Index(fields=['service_provider', 'status'], name='gateway_tra_service_0d473e_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewaytransaction',
            index=models.Index(fields=['status', '-created_at'], name='gateway_tra_status_08df26_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutschedule',
            index=models.Index(fields=['participant', 'payout_status'], name='payout_sche_partici_1bb3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutschedule',
            index=models.Index(fields=['payout_status', 'scheduled_for'], name='payout_sche_payout__b6ae58_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutschedule',
            index=models.Index(fields=['period_start', 'period_end'], name='payout_sche_period__223c10_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecatalog',
            index=models.Index(fields=['service_provider', 'is_active'], name='service_cat_service_efaca8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecatalog',
            index=models.Index(fields=['service_category', 'is_active'], name='service_cat_service_7dd374_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecatalog',
            index=models.Index(fields=['region_code', 'is_active'], name='service_cat_region__569a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecatalog',
            index=models.Index(fields=['service_provider_role', 'is_active'], name='service_cat_service_2fe31c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetransaction',
            index=models.Index(fields=['patient', 'status'], name='service_tra_patient_3957dc_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetransaction',
            index=models.Index(fields=['service_provider', 'status'], name='service_tra_service_a535de_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetransaction',
            index=models.Index(fields=['transaction_ref'], name='service_tra_transac_57de4c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetransaction',
            index=models.Index(fields=['service_type', 'status'], name='service_tra_service_6cef1b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetransaction',
            index=models.Index(fields=['region_code', '-created_at'], name='service_tra_region__19f3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionfee',
            index=models.Index(fields=['service_transaction'], name='transaction_service_6e9a19_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionfee',
            index=models.Index(fields=['fee_collected'], name='transaction_fee_col_3491e7_idx'),
        ),
    ]
