# Generated by Django 6.0 on 2025-12-13 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_staff_roles_and_increase_role_max_length'),
        ('payments', '0005_rename_user_to_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentrequest',
            name='payment_req_to_user_974bbe_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentrequest',
            name='payment_req_from_us_6082f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='transfer',
            name='transfers_from_us_b85efe_idx',
        ),
        migrations.RemoveIndex(
            model_name='transfer',
            name='transfers_to_user_161698_idx',
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['to_participant', 'status'], name='payment_req_to_part_b52853_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['from_participant', 'status'], name='payment_req_from_pa_99c8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['from_participant', 'status'], name='transfers_from_pa_14c623_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['to_participant', 'status'], name='transfers_to_part_14ebf5_idx'),
        ),
    ]
