# Generated by Django 6.0 on 2025-12-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentreceipt_billing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='invoice_sequence',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
