# Generated by Django 6.0 on 2025-12-16 09:35

from django.db import migrations


def fix_invoice_numbers(apps, schema_editor):
    """Update existing receipts with proper invoice numbers"""
    PaymentReceipt = apps.get_model('payments', 'PaymentReceipt')
    
    role_prefix_map = {
        'doctor': 'D',
        'hospital': 'H',
        'pharmacy': 'P',
        'insurance_company': 'I',
    }
    
    receipts = PaymentReceipt.objects.filter(
        invoice_number__isnull=False
    ).order_by('issued_at')
    
    sequence = 1
    for receipt in receipts:
        provider_role = None
        if receipt.issued_by:
            provider_role = receipt.issued_by.role
        elif receipt.service_transaction:
            provider_role = receipt.service_transaction.service_provider_role
        
        prefix = role_prefix_map.get(provider_role, 'T')
        invoice_number = f"#{prefix}{sequence:03d}"
        
        receipt.invoice_number = invoice_number
        receipt.invoice_sequence = sequence
        receipt.save(update_fields=['invoice_number', 'invoice_sequence'])
        
        sequence += 1


def reverse_fix(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentreceipt_invoice_sequence'),
    ]

    operations = [
        migrations.RunPython(fix_invoice_numbers, reverse_fix),
    ]
