# Generated by Django 6.0 on 2025-12-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_fix_invoice_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
