# Generated by Django 6.0 on 2025-12-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_paymentreceipt_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
