# Generated by Django 6.0 on 2025-12-18 16:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_paymentreceipt_reminded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, help_text='Accounting code', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_tax_deductible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'hospital', 'pharmacy', 'insurance_company']}, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'db_table': 'expense_categories',
                'ordering': ['name'],
                'unique_together': {('participant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo_url', models.URLField(blank=True, help_text='URL to clinic/organization logo')),
                ('logo_file', models.FileField(blank=True, null=True, upload_to='invoice_logos/%Y/%m/')),
                ('business_name', models.CharField(blank=True, help_text='Custom business name for invoices', max_length=255)),
                ('tagline', models.CharField(blank=True, help_text='Business tagline', max_length=255)),
                ('template_choice', models.CharField(choices=[('standard', 'Standard Template'), ('modern', 'Modern Template'), ('classic', 'Classic Template'), ('minimal', 'Minimal Template')], default='standard', max_length=20)),
                ('primary_color', models.CharField(default='#2563eb', help_text='Hex color code (e.g., #2563eb)', max_length=7)),
                ('secondary_color', models.CharField(default='#64748b', help_text='Secondary hex color', max_length=7)),
                ('accent_color', models.CharField(default='#f59e0b', help_text='Accent hex color', max_length=7)),
                ('invoice_prefix', models.CharField(blank=True, help_text="e.g., 'DR-KOU-', 'CLINIC-'", max_length=20)),
                ('invoice_number_format', models.CharField(default='{prefix}{year}-{sequence}', help_text='Format: {prefix}{year}-{sequence}, {prefix}{month}{year}-{sequence}', max_length=50)),
                ('next_invoice_number', models.IntegerField(default=1, help_text='Next invoice sequence number')),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID / VAT number', max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('header_text', models.TextField(blank=True, help_text='Custom text in invoice header')),
                ('footer_text', models.TextField(blank=True, default='Thank you for your business!', help_text='Custom text in invoice footer')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('payment_instructions', models.TextField(blank=True)),
                ('auto_generate_invoices', models.BooleanField(default=True, help_text='Automatically generate invoice after consultation/service')),
                ('include_qr_code', models.BooleanField(default=True)),
                ('include_payment_link', models.BooleanField(default=True)),
                ('send_invoice_email', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(limit_choices_to={'role__in': ['doctor', 'hospital', 'pharmacy', 'insurance_company']}, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice Settings',
                'verbose_name_plural': 'Invoice Settings',
                'db_table': 'invoice_settings',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(choices=[('supplier', 'Medical Supplier'), ('equipment', 'Equipment Vendor'), ('staff', 'Staff/Employee'), ('utility', 'Utility Provider'), ('service', 'Service Provider'), ('consultant', 'Consultant'), ('other', 'Other')], default='supplier', max_length=50)),
                ('vendor_code', models.CharField(blank=True, help_text='Custom vendor code/ID', max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('payment_terms', models.CharField(default='Net 30', help_text="e.g., 'Net 30', 'Due on Receipt', 'Net 60'", max_length=50)),
                ('bank_account', models.CharField(blank=True, max_length=255)),
                ('mobile_money_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'hospital', 'pharmacy', 'insurance_company']}, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendors',
                'ordering': ['vendor_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text="Vendor's invoice number", max_length=255)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='vendor_invoices/%Y/%m/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_invoices', to='payments.expensecategory')),
                ('participant', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'hospital', 'pharmacy', 'insurance_company']}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invoices', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payments.vendor')),
            ],
            options={
                'db_table': 'vendor_invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['participant', 'is_active'], name='vendors_partici_e83acb_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['vendor_type'], name='vendors_vendor__7b13ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('participant', 'vendor_code')},
        ),
        migrations.AddIndex(
            model_name='vendorinvoice',
            index=models.Index(fields=['participant', 'payment_status'], name='vendor_invo_partici_99db77_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorinvoice',
            index=models.Index(fields=['vendor', 'payment_status'], name='vendor_invo_vendor__a2ee58_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorinvoice',
            index=models.Index(fields=['due_date'], name='vendor_invo_due_dat_c0a10a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorinvoice',
            index=models.Index(fields=['invoice_date'], name='vendor_invo_invoice_27fded_idx'),
        ),
    ]
