# Generated by Django 6.0 on 2025-12-25 03:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_add_invoice_vendor_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('bank_account', 'Compte Bancaire'), ('mobile_money', 'Mobile Money')], help_text='Type de méthode de paiement', max_length=20)),
                ('bank_name', models.CharField(blank=True, help_text='Nom de la banque', max_length=100)),
                ('account_number', models.CharField(blank=True, help_text='Numéro de compte bancaire', max_length=50)),
                ('account_name', models.CharField(blank=True, help_text='Nom du titulaire du compte', max_length=200)),
                ('swift_code', models.CharField(blank=True, help_text='Code SWIFT/BIC (pour les virements internationaux)', max_length=20)),
                ('mobile_money_provider', models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('orange', 'Orange Money')], help_text='Fournisseur mobile money', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Numéro de téléphone mobile money', max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format: +22997000000', regex='^\\+?[1-9]\\d{1,14}$')])),
                ('gateway_provider', models.CharField(default='fedapay', help_text='Fournisseur de passerelle (Fedapay, etc.)', max_length=50)),
                ('gateway_account_id', models.CharField(blank=True, help_text='ID du compte dans la passerelle de paiement', max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Méthode de paiement vérifiée')),
                ('verification_code', models.CharField(blank=True, help_text='Code de vérification OTP', max_length=10)),
                ('verification_code_expires_at', models.DateTimeField(blank=True, help_text='Expiration du code de vérification', null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Date de vérification', null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Méthode de paiement principale (utilisée par défaut)')),
                ('status', models.CharField(choices=[('pending', 'En Attente de Vérification'), ('active', 'Actif'), ('suspended', 'Suspendu'), ('rejected', 'Rejeté')], default='pending', help_text='Statut de la méthode de paiement', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Raison du rejet (si applicable)')),
                ('notes', models.TextField(blank=True, help_text='Notes administratives')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(help_text='Participant fournisseur de services (médecin, hôpital, pharmacie, assurance)', limit_choices_to={'role__in': ['doctor', 'hospital', 'pharmacy', 'insurance', 'lab', 'imaging']}, on_delete=django.db.models.deletion.CASCADE, related_name='linked_payment_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participant_payment_methods',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('micro_deposit', 'Micro-Dépôt Bancaire'), ('otp', 'Code OTP')], max_length=20)),
                ('otp_code', models.CharField(blank=True, help_text='Code OTP envoyé', max_length=10)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_amount_1', models.DecimalField(blank=True, decimal_places=2, help_text='Premier montant de micro-dépôt (en XOF)', max_digits=10, null=True)),
                ('deposit_amount_2', models.DecimalField(blank=True, decimal_places=2, help_text='Deuxième montant de micro-dépôt (en XOF)', max_digits=10, null=True)),
                ('deposit_reference', models.CharField(blank=True, help_text='Référence de transaction du dépôt', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En Attente'), ('verified', 'Vérifié'), ('failed', 'Échoué'), ('expired', 'Expiré')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('attempt_count', models.IntegerField(default=0, help_text='Nombre de tentatives de vérification')),
                ('max_attempts', models.IntegerField(default=3, help_text='Nombre maximum de tentatives autorisées')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_attempts', to='payments.participantpaymentmethod')),
            ],
            options={
                'db_table': 'payment_method_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='participantpaymentmethod',
            index=models.Index(fields=['participant', 'is_primary', 'status'], name='participant_partici_f1784b_idx'),
        ),
        migrations.AddIndex(
            model_name='participantpaymentmethod',
            index=models.Index(fields=['participant', 'status'], name='participant_partici_908aee_idx'),
        ),
        migrations.AddIndex(
            model_name='participantpaymentmethod',
            index=models.Index(fields=['gateway_account_id'], name='participant_gateway_9e546b_idx'),
        ),
        migrations.AddConstraint(
            model_name='participantpaymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('status', 'active')), fields=('participant',), name='unique_primary_payment_method_per_participant'),
        ),
        migrations.AddIndex(
            model_name='paymentmethodverification',
            index=models.Index(fields=['payment_method', 'status'], name='payment_met_payment_d29a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethodverification',
            index=models.Index(fields=['status', 'otp_expires_at'], name='payment_met_status_058e3b_idx'),
        ),
    ]
