# Generated by Django 6.0 on 2025-12-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_participantpaymentmethod_paymentmethodverification_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='providerpayout',
            table='participant_payouts',
        ),
    ]
