# Generated by Django 6.0 on 2025-12-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_rename_provider_namespace_tables'),
    ]

    operations = [
        # Add composite index on GatewayTransaction (status, created_at) for admin filtering
        migrations.AddIndex(
            model_name='gatewaytransaction',
            index=models.Index(fields=['status', 'created_at'], name='gateway_txn_status_created_idx'),
        ),

        # Add index on FedaPayWebhookEvent (processed, created_at) for pending webhooks query
        migrations.AddIndex(
            model_name='fedapaywebhookevent',
            index=models.Index(fields=['processed', 'created_at'], name='webhook_processed_created_idx'),
        ),

        # Add composite index on ParticipantPaymentMethod (participant, method_type) for service provider queries
        migrations.AddIndex(
            model_name='participantpaymentmethod',
            index=models.Index(fields=['participant', 'method_type'], name='participant_pmt_method_idx'),
        ),
    ]
