# Generated by Django 6.0 on 2025-12-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_add_performance_indexes'),
    ]

    operations = [
        # Partial index for active payment methods only
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_active_payment_methods
                ON participant_payment_methods (participant_id, is_primary)
                WHERE status = 'active';
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_active_payment_methods;"
        ),

        # Partial index for pending webhooks only
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_pending_webhooks
                ON fedapay_webhook_events (created_at DESC)
                WHERE processed = false;
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_pending_webhooks;"
        ),
    ]
