# Generated by Django 6.0 on 2025-12-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_add_partial_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fedapaywebhookevent',
            name='webhook_processed_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='gatewaytransaction',
            name='gateway_txn_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='participantpaymentmethod',
            name='participant_pmt_method_idx',
        ),
    ]
