# Generated by Django 6.0 on 2025-12-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_remove_fedapaywebhookevent_webhook_processed_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fedapaytransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Unique key to prevent duplicate transactions during sync', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Unique key to prevent duplicate transactions during sync', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Unique key to prevent duplicate transactions during sync', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Unique key to prevent duplicate transactions during sync', max_length=255, null=True, unique=True),
        ),
    ]
