# Generated by Django 6.0 on 2025-12-26 13:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_add_idempotency_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpayout',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='doctorpayout',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='doctorpayout',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='doctorpayout',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='doctorpayout',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='doctorpayout',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorpayout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='doctorpayout',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='fedapaycustomer',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='fedapaycustomer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='fedapaycustomer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='fedapaycustomer',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='fedapaycustomer',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='fedapaycustomer',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='fedapaycustomer',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='fedapaypayout',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='fedapaypayout',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='fedapaypayout',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='fedapaypayout',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='fedapaypayout',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='fedapaypayout',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='fedapaypayout',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='fedapaytransaction',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='fedapaytransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='fedapaytransaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='fedapaytransaction',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='fedapaytransaction',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='fedapaytransaction',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='fedapaytransaction',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='fedapaywebhookevent',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='fedapaywebhookevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='fedapaywebhookevent',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='fedapaywebhookevent',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='fedapaywebhookevent',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='fedapaywebhookevent',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='fedapaywebhookevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='fedapaywebhookevent',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='feeledger',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='feeledger',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='feeledger',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='feeledger',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='feeledger',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='feeledger',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='financialchat',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='financialchat',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='financialchat',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='financialchat',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='financialchat',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='financialchat',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='financialchat',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='financialchatmessage',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='financialchatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='financialchatmessage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='financialchatmessage',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='financialchatmessage',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='financialchatmessage',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='financialchatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='financialchatmessage',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='healthtransaction',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='healthtransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='healthtransaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='healthtransaction',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='healthtransaction',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='healthtransaction',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='healthtransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='healthtransaction',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='linkedvendor',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='linkedvendor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='linkedvendor',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='linkedvendor',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='linkedvendor',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='linkedvendor',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='linkedvendor',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='participantgatewayaccount',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='participantgatewayaccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='participantgatewayaccount',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='participantgatewayaccount',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='participantgatewayaccount',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='participantgatewayaccount',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='participantgatewayaccount',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='participantphone',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='participantphone',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='participantphone',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='participantphone',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='participantphone',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='participantphone',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='participantphone',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='payoutschedule',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='payoutschedule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='payoutschedule',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='payoutschedule',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='payoutschedule',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='payoutschedule',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='payoutschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='payoutschedule',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='transfer',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AlterField(
            model_name='doctorpayout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='doctorpayout',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fedapaycustomer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='fedapaycustomer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fedapaycustomer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='fedapaypayout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='fedapaypayout',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fedapaypayout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='fedapaytransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='fedapaytransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fedapaytransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='fedapaywebhookevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='fedapaywebhookevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feeledger',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='feeledger',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feeledger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='financialchat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='financialchat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='financialchat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='financialchatmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='financialchatmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gatewaytransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='gatewaytransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='healthtransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='healthtransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='linkedvendor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='linkedvendor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='linkedvendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='participantgatewayaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='participantgatewayaccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participantgatewayaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='participantphone',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='participantphone',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participantphone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='payoutschedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='payoutschedule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='providerpayout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='providerpayout',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
    ]
