# Generated by Django 6.0 on 2025-12-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_standardize_to_usd_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaytransaction',
            name='amount_local',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in local currency', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in USD (reference)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.01, help_text='Platform commission rate (default 1%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='conversion_timestamp',
            field=models.DateTimeField(blank=True, help_text='Currency conversion time', null=True),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='currency_code',
            field=models.CharField(blank=True, help_text='Local currency code', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='exchange_rate_used',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate used', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='payment_context',
            field=models.CharField(choices=[('patient_service', 'Patient Service Payment'), ('b2b_supplier', 'B2B Supplier Payment'), ('payroll', 'Payroll Payment'), ('vendor_payment', 'Vendor Payment'), ('insurance_claim', 'Insurance Claim'), ('other', 'Other')], default='patient_service', help_text='Context/purpose of payment', max_length=50),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='amount_local',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in participant local currency', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in USD (reference currency)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='conversion_timestamp',
            field=models.DateTimeField(blank=True, help_text='When currency conversion was performed', null=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='currency_code',
            field=models.CharField(blank=True, help_text='Local currency code', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='exchange_rate_used',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate at transaction time', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='currency_code',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='exchange_rate_used',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='gross_amount_local',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross amount in local currency', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='gross_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross amount in USD', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='platform_fee_amount_local',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission in local currency', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='platform_fee_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission in USD', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='tax_amount_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Tax in local currency', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='tax_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Tax in USD', max_digits=12, null=True),
        ),
    ]
