# Generated by Django 6.0 on 2025-12-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_implement_final_payment_dual_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpayout',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='fedapaypayout',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='fedapaytransaction',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='gatewaytransaction',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='providerpayout',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='tax_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Tax in XOF', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
    ]
