# Generated by Django 6.0 on 2025-12-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_alter_doctorpayout_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfee',
            name='gross_amount_xof',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross amount in XOF (platform base currency)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='platform_fee_amount_xof',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission in XOF', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transactionfee',
            name='tax_amount_xof',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Tax in XOF', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='currency_code',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='gross_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DEPRECATED: Use gross_amount_xof', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='platform_fee_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DEPRECATED: Use platform_fee_amount_xof', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='tax_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='DEPRECATED: Use tax_amount_xof', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
    ]
