# Generated by Django 6.0 on 2026-01-01 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_add_missing_receipt_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedapaytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('service_payment', 'Service Payment'), ('service_payment', 'Service Payment'), ('refund', 'Refund'), ('payout', 'Payout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='issued_to_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='issued_to_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='issued_to_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='issued_to_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='line_items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_gateway',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='pdf_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='service_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=18.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='transaction_reference',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
