# Generated by Django 6.0 on 2026-01-01 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_alter_doctorpayout_created_by_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
