# Generated by Django 6.0 on 2026-01-02 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_paymentreceipt_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('online', 'En ligne')], default='cash', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='payments.paymentreceipt'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Payé'), ('PENDING', 'En attente'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('partially_paid', 'Partiellement payé'), ('overdue', 'En retard'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
