# Generated by Django 6.0 on 2026-01-03 00:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WearableDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True)),
                ('created_by_instance', models.UUIDField(blank=True, default=uuid.uuid4, help_text='UUID of instance that created this record')),
                ('modified_by_instance', models.UUIDField(blank=True, default=uuid.uuid4, help_text='UUID of instance that last modified this record')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True)),
                ('device_type', models.CharField(choices=[('google_fit', 'Google Fit'), ('apple_health', 'Apple Health'), ('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('samsung_health', 'Samsung Health'), ('whoop', 'Whoop'), ('oura', 'Oura Ring'), ('polar', 'Polar'), ('suunto', 'Suunto'), ('strava', 'Strava'), ('other', 'Other')], max_length=50)),
                ('device_name', models.CharField(max_length=200)),
                ('device_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='active', max_length=20)),
                ('access_token_encrypted', models.TextField(blank=True, null=True)),
                ('refresh_token_encrypted', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency', models.IntegerField(default=60, help_text='Sync frequency in minutes')),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('data_types_enabled', models.JSONField(default=dict, help_text='Which data types to sync')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wearable_devices',
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'device_type', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='WearableSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True)),
                ('created_by_instance', models.UUIDField(blank=True, default=uuid.uuid4, help_text='UUID of instance that created this record')),
                ('modified_by_instance', models.UUIDField(blank=True, default=uuid.uuid4, help_text='UUID of instance that last modified this record')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True)),
                ('sync_started_at', models.DateTimeField(auto_now_add=True)),
                ('sync_completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], max_length=20)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_stored', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list, help_text='List of errors encountered')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='wearable_devices.wearabledevice')),
            ],
            options={
                'db_table': 'wearable_sync_logs',
                'ordering': ['-sync_started_at'],
            },
        ),
        migrations.CreateModel(
            name='WearableData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True)),
                ('created_by_instance', models.UUIDField(blank=True, default=uuid.uuid4, help_text='UUID of instance that created this record')),
                ('modified_by_instance', models.UUIDField(blank=True, default=uuid.uuid4, help_text='UUID of instance that last modified this record')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True)),
                ('data_type', models.CharField(choices=[('heart_rate', 'Heart Rate'), ('steps', 'Steps'), ('distance', 'Distance'), ('calories', 'Calories'), ('sleep', 'Sleep'), ('blood_pressure', 'Blood Pressure'), ('blood_oxygen', 'Blood Oxygen (SpO2)'), ('body_temperature', 'Body Temperature'), ('weight', 'Weight'), ('bmi', 'BMI'), ('body_fat', 'Body Fat Percentage'), ('exercise', 'Exercise/Activity'), ('stress', 'Stress Level'), ('hydration', 'Hydration'), ('nutrition', 'Nutrition'), ('menstruation', 'Menstruation'), ('respiratory_rate', 'Respiratory Rate'), ('vo2_max', 'VO2 Max'), ('hrv', 'Heart Rate Variability')], max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional data points and context')),
                ('source_id', models.CharField(blank=True, help_text='Original ID from source', max_length=200, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_data', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='wearable_devices.wearabledevice')),
            ],
            options={
                'db_table': 'wearable_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient', 'data_type', 'timestamp'], name='wearable_da_patient_5eb108_idx'), models.Index(fields=['device', 'timestamp'], name='wearable_da_device__a96a61_idx'), models.Index(fields=['timestamp'], name='wearable_da_timesta_44ad25_idx')],
            },
        ),
    ]
