# Generated by Django 6.0 on 2026-01-03 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearable_devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wearabledevice',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='wearabledevice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('patient', 'device_type'), name='unique_active_device_per_patient'),
        ),
    ]
