# Generated by Django 5.2.9 on 2026-01-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearable_devices', '0002_alter_wearabledevice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearabledevice',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('paused', 'Paused'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='active', max_length=20),
        ),
    ]
