# Generated by Django 6.0 on 2025-12-13 22:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('package_type', models.CharField(choices=[('individual', 'Individual'), ('family', 'Family')], default='individual', max_length=20)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('consultation_discount_percentage', models.FloatField(default=0.0)),
                ('is_consultation_free', models.BooleanField(default=False)),
                ('coverage_details', models.JSONField(blank=True, default=dict)),
                ('premium_amount', models.IntegerField(default=0)),
                ('max_coverage_amount', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurance_packages',
            },
        ),
        migrations.CreateModel(
            name='HealthcarePartnerNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='active', max_length=20)),
                ('tier', models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('basic', 'Basic')], default='standard', max_length=20)),
                ('discount_percentage', models.FloatField(default=0.0)),
                ('contracted_rate', models.JSONField(blank=True, default=dict)),
                ('services_covered', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('terms_conditions', models.TextField(blank=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('patient_copay_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('healthcare_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_memberships', to=settings.AUTH_USER_MODEL)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_networks', to=settings.AUTH_USER_MODEL)),
                ('insurance_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_partners', to='insurance.insurancepackage')),
            ],
            options={
                'db_table': 'healthcare_partner_networks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_coverage_start', models.DateField()),
                ('applicant_details', models.JSONField(default=dict)),
                ('dependents_details', models.JSONField(blank=True, default=list)),
                ('medical_history', models.JSONField(blank=True, default=dict)),
                ('supporting_documents', models.JSONField(blank=True, default=list)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enrollments', to=settings.AUTH_USER_MODEL)),
                ('insurance_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='insurance.insurancepackage')),
            ],
            options={
                'db_table': 'enrollment_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_payment_date', models.DateField()),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('premium_amount', models.IntegerField()),
                ('payment_frequency', models.CharField(max_length=20)),
                ('total_paid', models.IntegerField(default=0)),
                ('payment_count', models.IntegerField(default=0)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_method', models.CharField(default='wallet', max_length=30)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='insurance.insurancepackage')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurance_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_invoices', to=settings.AUTH_USER_MODEL)),
                ('insurance_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='insurance.insurancepackage')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='insurance.insurancesubscription')),
            ],
            options={
                'db_table': 'insurance_invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientInsuranceCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=100, unique=True)),
                ('policy_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('coverage_start_date', models.DateField()),
                ('coverage_end_date', models.DateField()),
                ('beneficiaries', models.JSONField(blank=True, default=list)),
                ('card_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_cards', to='insurance.insurancepackage')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_insurance_cards',
            },
        ),
        migrations.AddField(
            model_name='insurancesubscription',
            name='insurance_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='insurance.patientinsurancecard'),
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(max_length=100, unique=True)),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation'), ('prescription', 'Prescription'), ('lab_test', 'Lab Test'), ('hospitalization', 'Hospitalization'), ('surgery', 'Surgery'), ('emergency', 'Emergency')], max_length=50)),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_id', models.UUIDField()),
                ('service_date', models.DateField()),
                ('claimed_amount', models.IntegerField()),
                ('approved_amount', models.IntegerField(default=0)),
                ('paid_amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('underReview', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='submitted', max_length=20)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_details', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('attachment_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to=settings.AUTH_USER_MODEL)),
                ('insurance_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.insurancepackage')),
                ('insurance_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.patientinsurancecard')),
            ],
            options={
                'db_table': 'insurance_claims',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='ClaimAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('medical_report', 'Medical Report'), ('prescription', 'Prescription'), ('invoice', 'Invoice'), ('lab_result', 'Lab Result'), ('xray', 'X-Ray'), ('receipt', 'Receipt'), ('referral_letter', 'Referral Letter'), ('diagnosis_certificate', 'Diagnosis Certificate'), ('other', 'Other')], max_length=30)),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_claim_attachments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_claim_attachments', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='insurance.insuranceclaim')),
            ],
            options={
                'db_table': 'claim_attachments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['claim', 'document_type'], name='claim_attac_claim_i_6ab71e_idx'), models.Index(fields=['is_verified'], name='claim_attac_is_veri_58cdf0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='insurancepackage',
            index=models.Index(fields=['company', 'is_active'], name='insurance_p_company_3e99ec_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcarepartnernetwork',
            index=models.Index(fields=['insurance_company', 'status'], name='healthcare__insuran_fd7020_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcarepartnernetwork',
            index=models.Index(fields=['healthcare_partner', 'status'], name='healthcare__healthc_66c03a_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcarepartnernetwork',
            index=models.Index(fields=['insurance_package'], name='healthcare__insuran_8ad9ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='healthcarepartnernetwork',
            unique_together={('insurance_company', 'healthcare_partner', 'insurance_package')},
        ),
        migrations.AddIndex(
            model_name='insuranceinvoice',
            index=models.Index(fields=['patient', 'status'], name='insurance_i_patient_81bed4_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceinvoice',
            index=models.Index(fields=['subscription'], name='insurance_i_subscri_408311_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceinvoice',
            index=models.Index(fields=['invoice_number'], name='insurance_i_invoice_b0a79c_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceinvoice',
            index=models.Index(fields=['due_date', 'status'], name='insurance_i_due_dat_c0c910_idx'),
        ),
        migrations.AddIndex(
            model_name='patientinsurancecard',
            index=models.Index(fields=['patient', 'status'], name='patient_ins_patient_212b96_idx'),
        ),
        migrations.AddIndex(
            model_name='patientinsurancecard',
            index=models.Index(fields=['card_number'], name='patient_ins_card_nu_6c5f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancesubscription',
            index=models.Index(fields=['patient', 'status'], name='insurance_s_patient_6143c8_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancesubscription',
            index=models.Index(fields=['next_payment_date', 'status'], name='insurance_s_next_pa_da5826_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['patient', 'status'], name='insurance_c_patient_2bdab1_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['claim_number'], name='insurance_c_claim_n_6e8b18_idx'),
        ),
    ]
