# Generated by Django 6.0 on 2025-12-14 05:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_rename_provider_to_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCoverageEnquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enquiry_number', models.CharField(max_length=100, unique=True)),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation'), ('prescription', 'Prescription'), ('lab_test', 'Laboratory Test'), ('imaging', 'Medical Imaging'), ('surgery', 'Surgery'), ('hospitalization', 'Hospitalization'), ('emergency', 'Emergency'), ('dental', 'Dental'), ('optical', 'Optical'), ('maternity', 'Maternity'), ('physiotherapy', 'Physiotherapy'), ('other', 'Other')], max_length=50)),
                ('service_name', models.CharField(max_length=255)),
                ('service_description', models.TextField()),
                ('estimated_cost', models.IntegerField()),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_type', models.CharField(max_length=50)),
                ('planned_date', models.DateField()),
                ('medical_necessity', models.TextField()),
                ('doctor_recommendation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('insurance_coverage_percentage', models.FloatField(blank=True, null=True)),
                ('insurance_covers_amount', models.IntegerField(blank=True, null=True)),
                ('patient_pays_amount', models.IntegerField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('attachment_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='insurance.patientinsurancecard')),
                ('insurance_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='insurance.insurancepackage')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_enquiries', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurance_coverage_enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='insurance_c_patient_b1801c_idx'), models.Index(fields=['insurance_package', 'status'], name='insurance_c_insuran_1f32aa_idx'), models.Index(fields=['enquiry_number'], name='insurance_c_enquiry_67eb14_idx')],
            },
        ),
    ]
