# Generated by Django 6.0 on 2025-12-14 06:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_insurancesubscription_approval_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_role', models.CharField(choices=[('claims_processor', 'Claims Processor'), ('underwriter', 'Underwriter'), ('customer_service', 'Customer Service'), ('manager', 'Manager'), ('administrator', 'Administrator')], max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=100)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_staff_members', to=settings.AUTH_USER_MODEL)),
                ('staff_participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_staff_profile', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_staff', to='insurance.insurancestaff')),
            ],
            options={
                'verbose_name': 'Insurance Staff',
                'verbose_name_plural': 'Insurance Staff',
                'db_table': 'insurance_staff',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['insurance_company', 'is_active'], name='insurance_s_insuran_4e2fcf_idx'), models.Index(fields=['staff_role'], name='insurance_s_staff_r_7f8543_idx')],
            },
        ),
    ]
