# Generated by Django 6.0 on 2025-12-24 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_add_insurance_operational_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='partner_id',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='partner_name',
        ),
        migrations.RemoveField(
            model_name='insurancecoverageenquiry',
            name='partner_name',
        ),
        migrations.RemoveField(
            model_name='insurancecoverageenquiry',
            name='partner_type',
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='healthcare_provider',
            field=models.ForeignKey(blank=True, help_text='Hospital, doctor, pharmacy, or other healthcare provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_insurance_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insurancecoverageenquiry',
            name='healthcare_provider',
            field=models.ForeignKey(blank=True, help_text='Hospital, doctor, pharmacy, or other healthcare provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_coverage_enquiries', to=settings.AUTH_USER_MODEL),
        ),
    ]
