# Generated by Django 6.0 on 2025-12-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_replace_partner_fields_with_healthcare_provider'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='providercontract',
            new_name='insurance_p_insuran_cb66b6_idx',
            old_name='provider_co_insuran_df76fc_idx',
        ),
        migrations.RenameIndex(
            model_name='providercontract',
            new_name='insurance_p_provide_bd9f99_idx',
            old_name='provider_co_provide_011fcb_idx',
        ),
        migrations.RenameIndex(
            model_name='providercontract',
            new_name='insurance_p_contrac_db1429_idx',
            old_name='provider_co_contrac_4e8511_idx',
        ),
        migrations.RenameIndex(
            model_name='providercontract',
            new_name='insurance_p_effecti_e261d6_idx',
            old_name='provider_co_effecti_a9a951_idx',
        ),
        migrations.RenameIndex(
            model_name='providercredential',
            new_name='insurance_p_insuran_409a5e_idx',
            old_name='provider_cr_insuran_71cdff_idx',
        ),
        migrations.RenameIndex(
            model_name='providercredential',
            new_name='insurance_p_provide_43551c_idx',
            old_name='provider_cr_provide_f0f546_idx',
        ),
        migrations.RenameIndex(
            model_name='providercredential',
            new_name='insurance_p_credent_508da5_idx',
            old_name='provider_cr_credent_cb295b_idx',
        ),
        migrations.RenameIndex(
            model_name='providercredential',
            new_name='insurance_p_expirat_408b5a_idx',
            old_name='provider_cr_expirat_559b29_idx',
        ),
        migrations.RenameIndex(
            model_name='providerperformance',
            new_name='insurance_p_insuran_ff6bcf_idx',
            old_name='provider_pe_insuran_4c64e7_idx',
        ),
        migrations.RenameIndex(
            model_name='providerperformance',
            new_name='insurance_p_measure_cd3b26_idx',
            old_name='provider_pe_measure_481d1e_idx',
        ),
        migrations.RenameIndex(
            model_name='providerperformance',
            new_name='insurance_p_outlier_74bd29_idx',
            old_name='provider_pe_outlier_fc351e_idx',
        ),
        migrations.AlterModelTable(
            name='providercontract',
            table='insurance_provider_contracts',
        ),
        migrations.AlterModelTable(
            name='providercredential',
            table='insurance_provider_credentials',
        ),
        migrations.AlterModelTable(
            name='providerperformance',
            table='insurance_provider_performance',
        ),
    ]
