# Generated by Django 6.0 on 2025-12-25 06:18

from django.db import migrations


def drop_orphaned_table(apps, schema_editor):
    """Drop orphaned provider_networks table that has no corresponding model"""
    schema_editor.execute("DROP TABLE IF EXISTS provider_networks CASCADE;")


def reverse_drop(apps, schema_editor):
    """Cannot recreate orphaned table - this is irreversible"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_rename_provider_namespace_tables'),
    ]

    operations = [
        migrations.RunPython(drop_orphaned_table, reverse_drop),
    ]
