# Generated by Django 6.0 on 2025-12-26 12:37

import django.utils.timezone
import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('insurance', '0011_claimattachment_created_by_instance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcarePartnerNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, help_text='Global unique identifier')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('created_by_instance', models.UUIDField(blank=True, null=True, help_text='UUID of instance that created this record')),
                ('modified_by_instance', models.UUIDField(blank=True, null=True, help_text='UUID of instance that last modified this record')),
                ('is_deleted', models.BooleanField(default=False, db_index=True, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, help_text='When this record was marked as deleted')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, help_text='When this record was last synced with cloud')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('region_code', models.CharField(max_length=50, default='global', db_index=True)),
                ('status', models.CharField(max_length=20, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='active')),
                ('tier', models.CharField(max_length=20, choices=[('premium', 'Premium'), ('standard', 'Standard'), ('basic', 'Basic')], default='standard')),
                ('discount_percentage', models.FloatField(default=0.0)),
                ('contracted_rate', models.JSONField(default=dict, blank=True)),
                ('services_covered', models.JSONField(default=list, blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True, blank=True)),
                ('contract_number', models.CharField(max_length=100, blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('patient_copay_percentage', models.FloatField(default=0.0)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_networks', to='core.participant')),
                ('healthcare_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_memberships', to='core.participant')),
                ('insurance_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_partners', to='insurance.insurancepackage')),
            ],
            options={
                'db_table': 'healthcare_partner_networks',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['insurance_company', 'status'], name='healthcare_insuran_ca3e48_idx'),
                    models.Index(fields=['healthcare_partner', 'status'], name='healthcare_healthc_5f8b29_idx'),
                    models.Index(fields=['insurance_package'], name='healthcare_insuran_a7d4f1_idx'),
                ],
                'unique_together': {('insurance_company', 'healthcare_partner', 'insurance_package')},
            },
        ),
    ]
