# Generated by Django 6.0 on 2025-12-26 12:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_create_healthcare_partner_networks_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='healthcarepartnernetwork',
            new_name='healthcare__insuran_fd7020_idx',
            old_name='healthcare_insuran_ca3e48_idx',
        ),
        migrations.RenameIndex(
            model_name='healthcarepartnernetwork',
            new_name='healthcare__healthc_66c03a_idx',
            old_name='healthcare_healthc_5f8b29_idx',
        ),
        migrations.RenameIndex(
            model_name='healthcarepartnernetwork',
            new_name='healthcare__insuran_8ad9ee_idx',
            old_name='healthcare_insuran_a7d4f1_idx',
        ),
        migrations.AddField(
            model_name='claimadjudicationresult',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='claimadjudicationresult',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='claimadjudicationresult',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='claimadjudicationresult',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='claimadjudicationresult',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='claimadjudicationresult',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='claimadjudicationresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='claimadjudicationresult',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='claimadjudicationrule',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='claimadjudicationrule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='claimadjudicationrule',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='claimadjudicationrule',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='claimadjudicationrule',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='claimadjudicationrule',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='claimadjudicationrule',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='copaydeductibleconfig',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='copaydeductibleconfig',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='copaydeductibleconfig',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='copaydeductibleconfig',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='copaydeductibleconfig',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='copaydeductibleconfig',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='copaydeductibleconfig',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='coveragerule',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='coveragerule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='coveragerule',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='coveragerule',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='coveragerule',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='coveragerule',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='coveragerule',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='feeschedule',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='graceperiod',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='graceperiod',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='graceperiod',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='graceperiod',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='graceperiod',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='graceperiod',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='graceperiod',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='insurancestaff',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='insurancestaff',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='insurancestaff',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='insurancestaff',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='insurancestaff',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='insurancestaff',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='insurancestaff',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='medicalnecessityreview',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='medicalnecessityreview',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='medicalnecessityreview',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='medicalnecessityreview',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='medicalnecessityreview',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='medicalnecessityreview',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='medicalnecessityreview',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='membershiprenewal',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='membershiprenewal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='membershiprenewal',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='membershiprenewal',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='membershiprenewal',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='membershiprenewal',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='membershiprenewal',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='providercontract',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='providercontract',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='providercontract',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='providercontract',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='providercontract',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='providercontract',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='providercontract',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='providerperformance',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='providerperformance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='providerperformance',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='providerperformance',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='providerperformance',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='providerperformance',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='providerperformance',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='underwritingapplication',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='underwritingapplication',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='underwritingapplication',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='underwritingapplication',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='underwritingapplication',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='underwritingapplication',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='underwritingapplication',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AlterField(
            model_name='claimadjudicationresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='claimadjudicationresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='claimadjudicationrule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='claimadjudicationrule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='claimadjudicationrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='copaydeductibleconfig',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='copaydeductibleconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='copaydeductibleconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='coveragerule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='coveragerule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coveragerule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='feeschedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='feeschedule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feeschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='graceperiod',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='graceperiod',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='graceperiod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='insurancestaff',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='insurancestaff',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insurancestaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='medicalnecessityreview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='medicalnecessityreview',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalnecessityreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='membershiprenewal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='membershiprenewal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membershiprenewal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='providercontract',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='providercontract',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='providercontract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='providercredential',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='providercredential',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='providercredential',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='providerperformance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='providerperformance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='providerperformance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='underwritingapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='underwritingapplication',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='underwritingapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
    ]
