# Generated by Django 6.0 on 2025-12-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_rename_healthcare_insuran_ca3e48_idx_healthcare__insuran_fd7020_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copaydeductibleconfig',
            name='annual_deductible',
            field=models.IntegerField(default=0, help_text='Annual deductible in USD cents'),
        ),
        migrations.AlterField(
            model_name='copaydeductibleconfig',
            name='out_of_pocket_maximum',
            field=models.IntegerField(blank=True, help_text='Annual OOP max in USD cents', null=True),
        ),
        migrations.AlterField(
            model_name='coveragerule',
            name='max_coverage_per_service',
            field=models.IntegerField(blank=True, help_text='Max amount per service in USD cents', null=True),
        ),
        migrations.AlterField(
            model_name='feeschedule',
            name='contracted_rate',
            field=models.IntegerField(blank=True, help_text='Negotiated rate with providers in USD cents', null=True),
        ),
        migrations.AlterField(
            model_name='feeschedule',
            name='maximum_allowed_amount',
            field=models.IntegerField(help_text='Max amount insurance will consider in USD cents'),
        ),
        migrations.AlterField(
            model_name='feeschedule',
            name='usual_and_customary_rate',
            field=models.IntegerField(help_text='Typical market rate in USD cents'),
        ),
        migrations.AlterField(
            model_name='providerperformance',
            name='bonus_earned',
            field=models.IntegerField(default=0, help_text='Performance bonus in USD cents'),
        ),
        migrations.AlterField(
            model_name='providerperformance',
            name='penalty_assessed',
            field=models.IntegerField(default=0, help_text='Performance penalty in USD cents'),
        ),
    ]
