# Generated by Django 6.0 on 2025-12-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0014_alter_copaydeductibleconfig_annual_deductible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancesubscription',
            name='payment_method',
            field=models.CharField(default='fedapay_mobile', help_text='Payment method: fedapay_mobile, fedapay_card, mtn_momo, moov_money, orange_money', max_length=50),
        ),
    ]
