# Generated by Django 6.0 on 2025-12-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_remove_wallet_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copaydeductibleconfig',
            name='annual_deductible',
            field=models.IntegerField(default=0, help_text='Annual deductible in XOF cents'),
        ),
        migrations.AlterField(
            model_name='copaydeductibleconfig',
            name='out_of_pocket_maximum',
            field=models.IntegerField(blank=True, help_text='Annual OOP max in XOF cents', null=True),
        ),
        migrations.AlterField(
            model_name='coveragerule',
            name='max_coverage_per_service',
            field=models.IntegerField(blank=True, help_text='Max amount per service in XOF cents', null=True),
        ),
        migrations.AlterField(
            model_name='feeschedule',
            name='contracted_rate',
            field=models.IntegerField(blank=True, help_text='Negotiated rate with providers in XOF cents', null=True),
        ),
        migrations.AlterField(
            model_name='feeschedule',
            name='maximum_allowed_amount',
            field=models.IntegerField(help_text='Max amount insurance will consider in XOF cents'),
        ),
        migrations.AlterField(
            model_name='feeschedule',
            name='usual_and_customary_rate',
            field=models.IntegerField(help_text='Typical market rate in XOF cents'),
        ),
        migrations.AlterField(
            model_name='insurancecoverageenquiry',
            name='estimated_cost',
            field=models.IntegerField(help_text='Estimated cost in XOF cents'),
        ),
        migrations.AlterField(
            model_name='insurancecoverageenquiry',
            name='insurance_covers_amount',
            field=models.IntegerField(blank=True, help_text='Amount covered in XOF cents', null=True),
        ),
        migrations.AlterField(
            model_name='insurancecoverageenquiry',
            name='patient_pays_amount',
            field=models.IntegerField(blank=True, help_text='Patient payment in XOF cents', null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinvoice',
            name='amount',
            field=models.IntegerField(help_text='Amount in XOF cents'),
        ),
        migrations.AlterField(
            model_name='insurancesubscription',
            name='premium_amount',
            field=models.IntegerField(help_text='Premium amount in XOF cents'),
        ),
        migrations.AlterField(
            model_name='insurancesubscription',
            name='total_paid',
            field=models.IntegerField(default=0, help_text='Total paid in XOF cents'),
        ),
        migrations.AlterField(
            model_name='providerperformance',
            name='bonus_earned',
            field=models.IntegerField(default=0, help_text='Performance bonus in XOF cents'),
        ),
        migrations.AlterField(
            model_name='providerperformance',
            name='penalty_assessed',
            field=models.IntegerField(default=0, help_text='Performance penalty in XOF cents'),
        ),
    ]
