# Generated by Django 6.0 on 2025-12-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0016_alter_copaydeductibleconfig_annual_deductible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Client-provided unique key to prevent duplicate claim submission', max_length=255, null=True, unique=True),
        ),
    ]
