# Generated by Django 6.0 on 2025-12-31 19:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0017_add_idempotency_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True)),
                ('created_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True)),
                ('modified_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('health_insurance', 'Assurance Santé'), ('dental_insurance', 'Assurance Dentaire'), ('optical_insurance', 'Assurance Optique'), ('maternity_coverage', 'Couverture Maternité'), ('life_insurance', 'Assurance Vie'), ('disability_insurance', 'Assurance Invalidité'), ('critical_illness', 'Maladie Grave'), ('travel_insurance', 'Assurance Voyage'), ('add_on_coverage', 'Couverture Additionnelle'), ('consultation', 'Consultation Assurance'), ('other', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('premium_amount', models.IntegerField(default=0, help_text='Premium in XOF cents')),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('semi_annual', 'Semestriel'), ('annual', 'Annuel')], default='monthly', max_length=20)),
                ('coverage_limit', models.IntegerField(blank=True, help_text='Maximum coverage in XOF cents', null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('minimum_age', models.IntegerField(blank=True, null=True)),
                ('maximum_age', models.IntegerField(blank=True, null=True)),
                ('waiting_period_days', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('insurance_company', models.ForeignKey(limit_choices_to={'role': 'insurance_company'}, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurance_services',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['insurance_company', 'is_active'], name='insurance_s_insuran_7ea61b_idx'), models.Index(fields=['category', 'is_available'], name='insurance_s_categor_aee61f_idx')],
            },
        ),
    ]
