# Generated by Django 6.0 on 2025-12-08 19:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_consultation_fee', models.DecimalField(decimal_places=2, default=5.0, help_text='Standard consultation fee for all appointments (base price)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_consultation_currency', models.CharField(default='EUR', help_text='Currency code for consultation fee (EUR, USD, XOF, etc.)', max_length=3)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=1.0, help_text='Platform fee percentage (e.g., 1.00 for 1%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=18.0, help_text='Tax percentage applied to platform fee (e.g., 18.00 for 18%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('wallet_topup_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for wallet top-ups (0 = free)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_configs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
                'db_table': 'system_configuration',
                'ordering': ['-created_at'],
            },
        ),
    ]
