# Generated by Django 6.0 on 2025-12-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_allow_null_wallet_for_cash_payments'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transportprovider',
            name='transport_p_status_84f75f_idx',
        ),
        migrations.DeleteModel(
            name='TransportProvider',
        ),
        migrations.RemoveIndex(
            model_name='transportrequest',
            name='transport_r_patient_fc6d42_idx',
        ),
        migrations.RemoveIndex(
            model_name='transportrequest',
            name='transport_r_request_cb1e85_idx',
        ),
        migrations.RemoveIndex(
            model_name='transportrequest',
            name='transport_r_schedul_cecd2e_idx',
        ),
        migrations.RemoveIndex(
            model_name='transportrequest',
            name='transport_r_status_032a66_idx',
        ),
        migrations.DeleteModel(
            name='TransportRequest',
        ),
    ]
