# Generated by Django 6.0 on 2025-12-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_transportprovider_transport_p_status_84f75f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('hospital', 'Hospital'), ('hospital_staff', 'Hospital Staff'), ('pharmacy', 'Pharmacy'), ('pharmacy_staff', 'Pharmacy Staff'), ('insurance_company', 'Insurance Company'), ('insurance_company_staff', 'Insurance Company Staff'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], max_length=30),
        ),
    ]
