# Generated by Django 6.0 on 2025-12-14 07:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_staff_roles_and_increase_role_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('other', 'Other')], max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary emergency contact')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_contacts',
                'ordering': ['-is_primary', 'full_name'],
                'indexes': [models.Index(fields=['participant', '-is_primary'], name='emergency_c_partici_c77b07_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParticipantPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', help_text='Display theme preference', max_length=10)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', help_text='Text size preference', max_length=10)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('ar', 'العربية')], default='fr', help_text='Preferred language', max_length=5)),
                ('enable_push_notifications', models.BooleanField(default=True, help_text='Receive push notifications for appointments and updates')),
                ('enable_email_notifications', models.BooleanField(default=True, help_text='Receive email notifications - affects actual emails sent')),
                ('enable_sms_notifications', models.BooleanField(default=False, help_text='Receive SMS notifications - affects actual SMS sent')),
                ('notify_appointment_confirmed', models.BooleanField(default=True)),
                ('notify_appointment_cancelled', models.BooleanField(default=True)),
                ('notify_appointment_reminder', models.BooleanField(default=True)),
                ('notify_prescription_ready', models.BooleanField(default=True)),
                ('notify_test_results', models.BooleanField(default=True)),
                ('notify_payment_received', models.BooleanField(default=True)),
                ('notify_payment_due', models.BooleanField(default=True)),
                ('notify_new_message', models.BooleanField(default=True)),
                ('notify_marketing', models.BooleanField(default=False)),
                ('appointment_reminder_time', models.IntegerField(choices=[(0, 'Disabled'), (15, '15 minutes before'), (30, '30 minutes before'), (60, '1 hour before'), (120, '2 hours before'), (1440, '1 day before')], default=60, help_text='Time before appointment to send reminder')),
                ('enable_two_factor_auth', models.BooleanField(default=False, help_text='Require 2FA for login')),
                ('profile_visible_to_providers', models.BooleanField(default=True, help_text='Allow healthcare providers to see profile')),
                ('allow_anonymous_data_sharing', models.BooleanField(default=False, help_text='Share anonymized data for medical research')),
                ('enable_auto_backup', models.BooleanField(default=True, help_text='Automatically backup documents and health records')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood type for emergency information', max_length=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant Preference',
                'verbose_name_plural': 'Participant Preferences',
                'db_table': 'participant_preferences',
                'indexes': [models.Index(fields=['participant'], name='participant_partici_bbe504_idx')],
            },
        ),
    ]
