# Generated by Django 6.0 on 2025-12-14 09:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emergencycontact_participantpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRepresentative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full legal name of the representative', max_length=255)),
                ('email', models.EmailField(help_text='Official email address of the representative', max_length=254)),
                ('phone_number', models.CharField(help_text='Direct phone number', max_length=20)),
                ('position', models.CharField(choices=[('ceo', 'Chief Executive Officer (CEO)'), ('director', 'Director'), ('general_manager', 'General Manager'), ('managing_director', 'Managing Director'), ('president', 'President'), ('vice_president', 'Vice President'), ('administrator', 'Administrator'), ('legal_officer', 'Legal Officer'), ('authorized_signatory', 'Authorized Signatory'), ('other', 'Other')], help_text='Official position in the organization', max_length=50)),
                ('position_other', models.CharField(blank=True, help_text='Specify if position is "Other"', max_length=100)),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID Card'), ('drivers_license', "Driver's License"), ('other', 'Other Government ID')], help_text='Type of identification document', max_length=20)),
                ('id_number', models.CharField(help_text='Identification document number', max_length=100)),
                ('id_expiry_date', models.DateField(blank=True, help_text='Expiration date of ID document', null=True)),
                ('id_document_front', models.FileField(help_text='Front side of ID document (passport, national ID, etc.)', upload_to='legal_representatives/id_documents/')),
                ('id_document_back', models.FileField(blank=True, help_text='Back side of ID document (if applicable)', upload_to='legal_representatives/id_documents/')),
                ('proof_of_position', models.FileField(blank=True, help_text='Document proving position (appointment letter, board resolution, etc.)', upload_to='legal_representatives/proof_documents/')),
                ('date_of_appointment', models.DateField(blank=True, help_text='Date appointed to current position', null=True)),
                ('authorization_scope', models.TextField(blank=True, help_text='Scope of authorization and signing authority')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the representative information has been verified by admin')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(limit_choices_to={'role__in': ['hospital', 'pharmacy', 'insurance_company']}, on_delete=django.db.models.deletion.CASCADE, related_name='legal_representative', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_representatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Representative',
                'verbose_name_plural': 'Legal Representatives',
                'db_table': 'legal_representatives',
            },
        ),
    ]
