# Generated by Django 6.0 on 2025-12-24 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_legalrepresentative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='default_consultation_currency',
            field=models.CharField(default='USD', help_text='Base currency for consultation fee (USD is platform default)', max_length=3),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='default_consultation_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Standard consultation fee for all appointments in USD (base price)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
