# Generated by Django 6.0 on 2025-12-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_update_existing_configs_to_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for location on Leaflet map', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for location on Leaflet map', max_digits=9, null=True),
        ),
    ]
