# Generated by Django 6.0 on 2025-12-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0010_add_geolocation_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['is_active'], name='participant_is_acti_48d6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['role', 'is_active'], name='participant_role_0e59a8_idx'),
        ),
    ]
