# Generated by Django 6.0 on 2025-12-25 03:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalStaffAffiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('affiliation_type', models.CharField(choices=[('staff', 'Personnel'), ('affiliated', 'Affilié')], help_text="Type d'affiliation", max_length=20)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('terminated', 'Terminé')], default='active', help_text="Statut de l'affiliation", max_length=20)),
                ('employment_start_date', models.DateField(blank=True, help_text="Date de début d'emploi", null=True)),
                ('employment_end_date', models.DateField(blank=True, help_text="Date de fin d'emploi", null=True)),
                ('job_title', models.CharField(blank=True, help_text='Titre du poste', max_length=200)),
                ('department', models.CharField(blank=True, help_text='Département', max_length=200)),
                ('can_manage_own_payments', models.BooleanField(default=False, help_text='Le médecin peut-il gérer ses propres paiements ? (Non si personnel)')),
                ('can_manage_own_claims', models.BooleanField(default=False, help_text='Le médecin peut-il gérer ses propres réclamations ? (Non si personnel)')),
                ('contract_document', models.FileField(blank=True, help_text='Document de contrat', null=True, upload_to='hospital_contracts/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Créé par (admin hôpital ou médecin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_affiliations', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(help_text='Médecin affilié', limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_affiliation_records', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(help_text='Hôpital employeur', limit_choices_to={'role': 'hospital'}, on_delete=django.db.models.deletion.CASCADE, related_name='employed_staff_doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_staff_affiliations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('view_patients', 'Voir les Patients'), ('manage_appointments', 'Gérer les Rendez-vous'), ('manage_prescriptions', 'Gérer les Prescriptions'), ('view_financial', 'Voir les Finances'), ('manage_financial', 'Gérer les Finances'), ('manage_claims', 'Gérer les Réclamations'), ('view_reports', 'Voir les Rapports')], max_length=50)),
                ('granted', models.BooleanField(default=True, help_text='Permission accordée')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.hospitalstaffaffiliation')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_staff_permissions',
            },
        ),
        migrations.AddIndex(
            model_name='hospitalstaffaffiliation',
            index=models.Index(fields=['doctor', 'status'], name='hospital_st_doctor__649068_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalstaffaffiliation',
            index=models.Index(fields=['hospital', 'status'], name='hospital_st_hospita_4e02e1_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalstaffaffiliation',
            index=models.Index(fields=['affiliation_type', 'status'], name='hospital_st_affilia_9e8ae9_idx'),
        ),
        migrations.AddConstraint(
            model_name='hospitalstaffaffiliation',
            constraint=models.UniqueConstraint(condition=models.Q(('affiliation_type', 'staff'), ('status', 'active')), fields=('doctor',), name='unique_active_staff_per_doctor'),
        ),
        migrations.AlterUniqueTogether(
            name='staffpermission',
            unique_together={('affiliation', 'permission')},
        ),
    ]
