# Generated by Django 6.0 on 2025-12-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_hospitalstaffaffiliation_staffpermission_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='providerservice',
            new_name='participant_provide_86309b_idx',
            old_name='provider_se_provide_7ab835_idx',
        ),
        migrations.RenameIndex(
            model_name='providerservice',
            new_name='participant_is_acti_d65640_idx',
            old_name='provider_se_is_acti_78f2bd_idx',
        ),
        migrations.AlterModelTable(
            name='providerdata',
            table='participant_provider_data',
        ),
        migrations.AlterModelTable(
            name='providerservice',
            table='participant_services',
        ),
    ]
