# Generated by Django 6.0 on 2025-12-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_provider_namespace_tables'),
    ]

    operations = [
        # Add index on HospitalStaffAffiliation created_by for audit queries
        migrations.AddIndex(
            model_name='hospitalstaffaffiliation',
            index=models.Index(fields=['created_by'], name='staff_affil_created_by_idx'),
        ),
    ]
