# Generated by Django 6.0 on 2025-12-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_performance_indexes'),
    ]

    operations = [
        # Add check constraint for valid employment dates
        migrations.AddConstraint(
            model_name='hospitalstaffaffiliation',
            constraint=models.CheckConstraint(
                condition=models.Q(employment_end_date__isnull=True) | models.Q(employment_end_date__gte=models.F('employment_start_date')),
                name='valid_employment_dates'
            ),
        ),
    ]
