# Generated by Django 6.0 on 2025-12-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_business_rule_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hospitalstaffaffiliation',
            name='valid_employment_dates',
        ),
        migrations.RemoveIndex(
            model_name='hospitalstaffaffiliation',
            name='staff_affil_created_by_idx',
        ),
    ]
