# Generated by Django 6.0 on 2025-12-25 12:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_hospitalstaffaffiliation_valid_employment_dates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewed_type', models.CharField(choices=[('doctor', 'Doctor'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('insurance', 'Insurance Company')], max_length=20)),
                ('reviewed_id', models.UUIDField(help_text='UUID of the doctor, hospital, pharmacy, or insurance company')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation'), ('telemedicine', 'Telemedicine'), ('prescription', 'Prescription'), ('pharmacy_service', 'Pharmacy Service'), ('insurance_claim', 'Insurance Claim'), ('hospital_service', 'Hospital Service'), ('emergency', 'Emergency Service'), ('surgery', 'Surgery'), ('diagnostic', 'Diagnostic Service'), ('other', 'Other')], max_length=30)),
                ('review_text', models.TextField(blank=True, help_text='Optional review comments')),
                ('professionalism_rating', models.IntegerField(blank=True, help_text='Professionalism and courtesy', null=True)),
                ('communication_rating', models.IntegerField(blank=True, help_text='Communication quality', null=True)),
                ('facility_rating', models.IntegerField(blank=True, help_text='Facility cleanliness and quality', null=True)),
                ('wait_time_rating', models.IntegerField(blank=True, help_text='Wait time satisfaction', null=True)),
                ('value_rating', models.IntegerField(blank=True, help_text='Value for money', null=True)),
                ('appointment_id', models.UUIDField(blank=True, help_text='Related appointment ID', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by system as genuine review')),
                ('is_approved', models.BooleanField(default=True, help_text='Approved for display')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured review')),
                ('provider_response', models.TextField(blank=True, help_text='Response from service provider')),
                ('provider_responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reviewed_type', 'reviewed_id', '-created_at'], name='reviews_reviewe_ac63e8_idx'), models.Index(fields=['reviewer', '-created_at'], name='reviews_reviewe_ae7fe9_idx'), models.Index(fields=['reviewed_type', 'reviewed_id', 'rating'], name='reviews_reviewe_fea2a6_idx'), models.Index(fields=['appointment_id'], name='reviews_appoint_83fef1_idx'), models.Index(fields=['is_approved', '-created_at'], name='reviews_is_appr_48b62f_idx')],
                'unique_together': {('reviewer', 'appointment_id')},
            },
        ),
    ]
