# Generated by Django 6.0 on 2025-12-26 22:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_syncmixin_to_core_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalequipment',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='review',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='review',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AlterField(
            model_name='medicalequipment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='medicalequipment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalequipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
    ]
