# Generated by Django 6.0 on 2025-12-26 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_standardize_to_usd_currency'),
    ]

    operations = [
        # Enhance Transaction model for Final Payment specification
        migrations.AddField(
            model_name='transaction',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Reference amount in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_local',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in participant local currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_code',
            field=models.CharField(default='USD', help_text='Local currency code used for payment', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate_used',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate at time of transaction', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='conversion_timestamp',
            field=models.DateTimeField(blank=True, help_text='When currency conversion was applied', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='commission_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='BintaCura 1% commission in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='commission_amount_local',
            field=models.DecimalField(decimal_places=2, default=0, help_text='BintaCura 1% commission in local currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, help_text='External gateway transaction ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_reference',
            field=models.CharField(blank=True, help_text='External gateway reference number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_name',
            field=models.CharField(blank=True, help_text='Payment gateway used (FedaPay, etc)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_context',
            field=models.CharField(choices=[('patient_service', 'Patient Service Payment'), ('b2b_supplier', 'B2B Supplier Payment'), ('payroll', 'Payroll/Staff Payment'), ('other', 'Other')], default='patient_service', help_text='Type of payment transaction', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='resolved_country',
            field=models.CharField(blank=True, help_text='Country resolved from phone + geolocation', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='resolution_method',
            field=models.CharField(blank=True, help_text='How currency was resolved: phone/geo/combined', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax amount (18% where applicable)', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='webhook_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Full webhook payload from gateway'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='webhook_received_at',
            field=models.DateTimeField(blank=True, help_text='When webhook was received', null=True),
        ),
        # Make Wallet.balance nullable for gradual transition to ledger-only model
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.00, help_text='DEPRECATED: Use computed ledger balance instead', max_digits=12, null=True),
        ),
        # Add index for gateway lookups
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['gateway_transaction_id'], name='core_txn_gateway_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_context'], name='core_txn_context_idx'),
        ),
    ]
