# Generated by Django 6.0 on 2025-12-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_enhance_transaction_for_final_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('lab_technician', 'Lab Technician'), ('administrator', 'Administrator'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier'), ('inventory_clerk', 'Inventory Clerk'), ('delivery_person', 'Delivery Person'), ('manager', 'Manager'), ('claims_processor', 'Claims Processor'), ('underwriter', 'Underwriter'), ('customer_service', 'Customer Service')], max_length=50),
        ),
    ]
