# Generated by Django 6.0 on 2025-12-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_participant_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerservice',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='default_consultation_currency',
            field=models.CharField(default='XOF', help_text='Base currency for consultation fee (XOF is platform default)', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Reference amount in XOF', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='BintaCura 1% commission in XOF', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_code',
            field=models.CharField(default='XOF', help_text='Local currency code used for payment', max_length=3),
        ),
    ]
