# Generated by Django 6.0 on 2025-12-30 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_syncmixin_fields_to_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='default_consultation_currency',
            field=models.CharField(default='XOF', help_text='Base currency for consultation fee (from settings.DEFAULT_CURRENCY)', max_length=3),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='default_consultation_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Standard consultation fee for all appointments (base price)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
