# Generated by Django 6.0 on 2025-12-30 22:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_create_participant_services_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True)),
                ('created_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True)),
                ('modified_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('consultation', 'Consultation'), ('surgery', 'Surgery'), ('diagnostic', 'Diagnostic'), ('laboratory', 'Laboratory'), ('imaging', 'Imaging'), ('therapy', 'Therapy'), ('pharmacy', 'Pharmacy'), ('emergency', 'Emergency'), ('vaccination', 'Vaccination'), ('dental', 'Dental'), ('maternity', 'Maternity'), ('pediatric', 'Pediatric'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
            ],
            options={
                'db_table': 'participant_services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='providerservice',
            name='participant_provide_86309b_idx',
        ),
        migrations.RemoveIndex(
            model_name='providerservice',
            name='participant_is_acti_d65640_idx',
        ),
        migrations.AddField(
            model_name='participantservice',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='providerservice',
            name='provider',
        ),
        migrations.AddIndex(
            model_name='participantservice',
            index=models.Index(fields=['participant', 'category'], name='participant_partici_f669c6_idx'),
        ),
        migrations.AddIndex(
            model_name='participantservice',
            index=models.Index(fields=['is_active', 'is_available'], name='participant_is_acti_d65640_idx'),
        ),
    ]
