# Generated by Django 6.0 on 2025-12-30 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_alter_appointment_service_and_more'),
        ('core', '0027_participantservice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderService',
        ),
    ]
