# Generated by Django 6.0 on 2025-12-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_delete_providerservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_xof',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Reference amount in XOF (platform base currency)', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='commission_amount_xof',
            field=models.DecimalField(decimal_places=2, default=0, help_text='BintaCura 1% commission in XOF', max_digits=12),
        ),
        migrations.AlterField(
            model_name='participant',
            name='preferred_currency',
            field=models.CharField(blank=True, default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='DEPRECATED: Use amount_xof instead', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='DEPRECATED: Use commission_amount_xof instead', max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('XOF', 'Franc CFA UEMOA'), ('XAF', 'Franc CFA CEMAC'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('ZAR', 'South African Rand'), ('KES', 'Kenyan Shilling'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('DZD', 'Algerian Dinar'), ('TND', 'Tunisian Dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('INR', 'Indian Rupee'), ('KRW', 'South Korean Won'), ('BRL', 'Brazilian Real'), ('RUB', 'Russian Ruble'), ('MXN', 'Mexican Peso'), ('SEK', 'Swedish Krona'), ('NOK', 'Norwegian Krone'), ('DKK', 'Danish Krone'), ('PLN', 'Polish Zloty'), ('TRY', 'Turkish Lira'), ('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar'), ('NZD', 'New Zealand Dollar'), ('THB', 'Thai Baht'), ('MYR', 'Malaysian Ringgit'), ('IDR', 'Indonesian Rupiah'), ('PHP', 'Philippine Peso'), ('VND', 'Vietnamese Dong'), ('ARS', 'Argentine Peso'), ('CLP', 'Chilean Peso'), ('COP', 'Colombian Peso'), ('PEN', 'Peruvian Sol'), ('ILS', 'Israeli Shekel')], default='XOF', max_length=3),
        ),
    ]
