# Generated by Django 6.0 on 2025-12-31 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_fix_currency_defaults_to_xof'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='can_receive_payments',
            field=models.BooleanField(default=False, help_text='Whether this provider can receive payments from patients'),
        ),
        migrations.AddField(
            model_name='participant',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes about verification'),
        ),
        migrations.AddField(
            model_name='participant',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the account was verified by admin', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regionalconfiguration',
            name='default_consultation_fee',
            field=models.IntegerField(default=3500, help_text='Default consultation fee in local currency (XOF cents for West Africa)'),
        ),
        migrations.AlterField(
            model_name='participantservice',
            name='category',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('surgery', 'Surgery'), ('diagnostic', 'Diagnostic'), ('laboratory', 'Laboratory'), ('imaging', 'Imaging'), ('therapy', 'Therapy'), ('pharmacy', 'Pharmacy'), ('emergency', 'Emergency'), ('vaccination', 'Vaccination'), ('dental', 'Dental'), ('maternity', 'Maternity'), ('pediatric', 'Pediatric'), ('insurance', 'Insurance Product/Service'), ('other', 'Other')], max_length=50),
        ),
    ]
