# Generated by Django 6.0 on 2025-12-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_participant_can_receive_payments_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='refundrequest',
            name='refund_requ_provide_40b426_idx',
        ),
        migrations.RenameField(
            model_name='refundrequest',
            old_name='provider',
            new_name='participant',
        ),
        migrations.AlterField(
            model_name='participant',
            name='can_receive_payments',
            field=models.BooleanField(default=False, help_text='Whether this participant can receive payments from patients'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['participant', 'status'], name='refund_requ_partici_6f2f1c_idx'),
        ),
    ]
