# Generated by Django 6.0 on 2025-12-31 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_refundrequest_refund_requ_provide_40b426_idx_and_more'),
        ('insurance', '0017_add_idempotency_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Client-provided unique key to prevent duplicate refund requests', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='insurance_claim',
            field=models.ForeignKey(blank=True, help_text='Link to insurance claim if refund is related to insurance payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_refund_requests', to='insurance.insuranceclaim'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['idempotency_key'], name='refund_requ_idempot_bef649_idx'),
        ),
        migrations.AddConstraint(
            model_name='refundrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'),
        ),
    ]
