# Generated by Django 6.0 on 2025-12-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_refund_security_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for account rejection'),
        ),
        migrations.AddField(
            model_name='participant',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', help_text='Account verification status for service providers', max_length=20),
        ),
    ]
