# Generated by Django 6.0 on 2026-01-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_fix_activation_code_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecompanydata',
            name='activation_code',
            field=models.CharField(blank=True, help_text='12-character alphanumeric activation code for local instance', max_length=14),
        ),
    ]
