# Generated by Django 6.0 on 2026-01-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_insurancecompanydata_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompanydata',
            name='activation_code_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the activation code expires', null=True),
        ),
        migrations.AddField(
            model_name='insurancecompanydata',
            name='activation_code_issued_at',
            field=models.DateTimeField(blank=True, help_text='When the activation code was issued', null=True),
        ),
        migrations.AddField(
            model_name='insurancecompanydata',
            name='activation_code_validity_years',
            field=models.IntegerField(default=1, help_text='Number of years the activation code is valid (default: 1 year)'),
        ),
    ]
