# Generated by Django 6.0 on 2026-01-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_activation_code_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Notification preferences for the participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='unread_messages_count',
            field=models.IntegerField(default=0, help_text='Count of unread messages'),
        ),
        migrations.AddField(
            model_name='participant',
            name='unread_notifications_count',
            field=models.IntegerField(default=0, help_text='Count of unread notifications'),
        ),
    ]
