# Generated by Django 6.0 on 2026-01-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_notification_fields_to_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalequipment',
            name='category',
            field=models.CharField(choices=[('diagnostic', 'Diagnostic'), ('surgical', 'Surgical'), ('life_support', 'Life Support'), ('monitoring', 'Monitoring'), ('therapeutic', 'Therapeutic'), ('laboratory', 'Laboratory'), ('vehicle', 'Vehicle'), ('other', 'Other')], max_length=50),
        ),
    ]
