# Generated by Django 6.0 on 2025-12-07 00:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('total_patients', models.IntegerField(default=0)),
                ('total_doctors', models.IntegerField(default=0)),
                ('total_hospitals', models.IntegerField(default=0)),
                ('total_pharmacies', models.IntegerField(default=0)),
                ('total_insurance_companies', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('active_users_today', models.IntegerField(default=0)),
                ('total_appointments', models.IntegerField(default=0)),
                ('completed_appointments', models.IntegerField(default=0)),
                ('cancelled_appointments', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_transaction_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_platform_fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_prescriptions', models.IntegerField(default=0)),
                ('fulfilled_prescriptions', models.IntegerField(default=0)),
                ('total_insurance_claims', models.IntegerField(default=0)),
                ('approved_claims', models.IntegerField(default=0)),
                ('verified_providers', models.IntegerField(default=0)),
                ('pending_verifications', models.IntegerField(default=0)),
                ('total_refund_requests', models.IntegerField(default=0)),
                ('pending_refunds', models.IntegerField(default=0)),
                ('approved_refunds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Statistics',
                'db_table': 'platform_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('platform_fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('appointment_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prescription_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('insurance_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('refunds_issued', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_count', models.IntegerField(default=0)),
                ('average_transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'revenue_metrics',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='UserGrowthMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('user_role', models.CharField(max_length=50)),
                ('new_registrations', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_growth_metrics',
                'indexes': [models.Index(fields=['date', 'user_role'], name='user_growth_date_0c893e_idx')],
                'unique_together': {('date', 'user_role')},
            },
        ),
    ]
