# Generated by Django 6.0 on 2025-12-10 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('PND', 'Prefer Not to Disclose')], max_length=4)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('feature_suggestion', models.TextField(blank=True)),
                ('other_suggestion', models.TextField(blank=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'survey_responses',
                'ordering': ['-submission_date'],
                'indexes': [models.Index(fields=['country'], name='survey_resp_country_2b607f_idx'), models.Index(fields=['profession'], name='survey_resp_profess_934394_idx'), models.Index(fields=['sex'], name='survey_resp_sex_52e47e_idx'), models.Index(fields=['submission_date'], name='survey_resp_submiss_601315_idx')],
            },
        ),
    ]
