# Generated by Django 6.0 on 2025-12-25 23:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_index=True, help_text="Full model path (e.g., 'appointments.Appointment')", max_length=100)),
                ('object_id', models.UUIDField(db_index=True, help_text='UUID of the object that changed')),
                ('event_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], help_text='Type of change: create, update, or delete', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this event occurred')),
                ('instance_id', models.UUIDField(blank=True, db_index=True, help_text='Which local instance created this event (null for cloud)', null=True)),
                ('data_snapshot', models.JSONField(help_text='Full serialized object data')),
                ('changed_fields', models.JSONField(blank=True, help_text='List of changed field names (for updates)', null=True)),
                ('data_hash', models.CharField(help_text='SHA256 hash of data_snapshot for integrity verification', max_length=64)),
                ('synced_to_cloud', models.BooleanField(db_index=True, default=False, help_text='Whether this event has been synced to cloud')),
                ('synced_at', models.DateTimeField(blank=True, help_text='When this event was synced to cloud', null=True)),
                ('conflict_detected', models.BooleanField(db_index=True, default=False, help_text='Whether a conflict was detected for this event')),
                ('conflict_resolution', models.CharField(blank=True, help_text='How the conflict was resolved', max_length=50, null=True)),
            ],
            options={
                'db_table': 'sync_events',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['model_name', 'timestamp'], name='sync_events_model_n_f0e0ca_idx'), models.Index(fields=['instance_id', 'synced_to_cloud'], name='sync_events_instanc_f46a34_idx'), models.Index(fields=['timestamp', 'synced_to_cloud'], name='sync_events_timesta_dc4bf8_idx'), models.Index(fields=['object_id', 'event_type'], name='sync_events_object__39d7e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncInstance',
            fields=[
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this installation', primary_key=True, serialize=False)),
                ('instance_type', models.CharField(choices=[('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('insurance', 'Insurance Company'), ('lab', 'Laboratory'), ('imaging', 'Imaging Center')], help_text='Type of organization', max_length=20)),
                ('instance_name', models.CharField(help_text="Descriptive name (e.g., 'Hospital Yalgado Desktop 1')", max_length=200)),
                ('platform', models.CharField(help_text="Operating system: 'windows', 'linux', etc.", max_length=20)),
                ('hardware_id', models.CharField(blank=True, help_text='Hardware identifier (MAC address, etc.)', max_length=200, null=True)),
                ('os_version', models.CharField(blank=True, help_text='OS version string', max_length=100, null=True)),
                ('api_key', models.CharField(db_index=True, help_text='API key for this instance (stored in plain text)', max_length=200, unique=True)),
                ('api_secret_hash', models.CharField(help_text='Hashed API secret (use make_password/check_password)', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this instance is allowed to sync')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this instance was registered')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='When this instance last synced', null=True)),
                ('sync_interval_minutes', models.IntegerField(default=15, help_text='How often to auto-sync (in minutes)')),
                ('sync_enabled', models.BooleanField(default=True, help_text='Whether automatic sync is enabled')),
                ('organization', models.ForeignKey(help_text='The hospital, pharmacy, or insurance company this instance belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sync_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_instances',
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(choices=[('update_update', 'Update-Update Conflict'), ('delete_update', 'Delete-Update Conflict'), ('create_create', 'Create-Create Conflict'), ('payment', 'Payment Conflict (Critical)'), ('other', 'Other Conflict')], help_text='Type of conflict detected', max_length=20)),
                ('model_name', models.CharField(help_text='Model that has conflicting versions', max_length=100)),
                ('object_id', models.UUIDField(help_text='ID of the object with conflict')),
                ('local_version', models.JSONField(help_text="Local instance's version of the object")),
                ('cloud_version', models.JSONField(help_text="Cloud database's version of the object")),
                ('resolution_strategy', models.CharField(blank=True, choices=[('cloud_wins', 'Cloud Version Wins'), ('local_wins', 'Local Version Wins'), ('latest_wins', 'Latest Timestamp Wins'), ('merge', 'Merge Changes'), ('manual', 'Manual Resolution Required')], help_text='How this conflict was/will be resolved', max_length=20, null=True)),
                ('resolved', models.BooleanField(db_index=True, default=False, help_text='Whether conflict has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When conflict was resolved', null=True)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When conflict was detected')),
                ('requires_manual_resolution', models.BooleanField(db_index=True, default=False, help_text='Whether auto-resolution failed and manual intervention needed')),
                ('notes', models.TextField(blank=True, help_text='Notes about conflict resolution', null=True)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who manually resolved the conflict', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(help_text='Instance where conflict was detected', on_delete=django.db.models.deletion.CASCADE, to='sync.syncinstance')),
            ],
            options={
                'db_table': 'sync_conflicts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncInstanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('push', 'Local → Cloud'), ('pull', 'Cloud → Local')], help_text='Push to cloud or pull from cloud', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='pending', help_text='Current status of sync operation', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When sync started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When sync completed', null=True)),
                ('records_pushed', models.IntegerField(default=0, help_text='Number of records pushed to cloud')),
                ('records_pulled', models.IntegerField(default=0, help_text='Number of records pulled from cloud')),
                ('conflicts_detected', models.IntegerField(default=0, help_text='Number of conflicts detected')),
                ('errors_count', models.IntegerField(default=0, help_text='Number of errors encountered')),
                ('error_message', models.TextField(blank=True, help_text='Error message if sync failed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional sync metadata')),
                ('instance', models.ForeignKey(help_text='Which instance performed this sync', on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='sync.syncinstance')),
            ],
            options={
                'db_table': 'sync_instance_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='syncinstance',
            index=models.Index(fields=['organization', 'is_active'], name='sync_instan_organiz_defc40_idx'),
        ),
        migrations.AddIndex(
            model_name='syncinstance',
            index=models.Index(fields=['api_key'], name='sync_instan_api_key_a64925_idx'),
        ),
        migrations.AddIndex(
            model_name='syncinstance',
            index=models.Index(fields=['instance_type'], name='sync_instan_instanc_3efe36_idx'),
        ),
        migrations.AddIndex(
            model_name='syncconflict',
            index=models.Index(fields=['resolved', 'requires_manual_resolution'], name='sync_confli_resolve_c23de0_idx'),
        ),
        migrations.AddIndex(
            model_name='syncconflict',
            index=models.Index(fields=['model_name', 'object_id'], name='sync_confli_model_n_861d50_idx'),
        ),
        migrations.AddIndex(
            model_name='syncconflict',
            index=models.Index(fields=['conflict_type'], name='sync_confli_conflic_9c67c1_idx'),
        ),
        migrations.AddIndex(
            model_name='syncconflict',
            index=models.Index(fields=['detected_at'], name='sync_confli_detecte_41bf29_idx'),
        ),
        migrations.AddIndex(
            model_name='syncinstancelog',
            index=models.Index(fields=['instance', 'status'], name='sync_instan_instanc_a45ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='syncinstancelog',
            index=models.Index(fields=['started_at'], name='sync_instan_started_bf238d_idx'),
        ),
        migrations.AddIndex(
            model_name='syncinstancelog',
            index=models.Index(fields=['direction', 'status'], name='sync_instan_directi_2697d7_idx'),
        ),
    ]
