# Generated by Django 6.0 on 2025-12-07 00:47

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal title for the ad (not displayed to users)', max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the ad background', null=True, upload_to='ads/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('video', models.FileField(blank=True, help_text='Upload a video for the ad background', null=True, upload_to='ads/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])])),
                ('heading', models.CharField(help_text='Main heading displayed on the ad', max_length=150)),
                ('subheading', models.CharField(blank=True, help_text='Subheading or description (optional)', max_length=200)),
                ('button_text', models.CharField(default='Learn More', help_text='Text displayed on the button', max_length=50)),
                ('button_link', models.URLField(help_text='URL the button links to (can be internal or external)', max_length=500)),
                ('button_opens_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When to start showing this ad')),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing this ad (optional)', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in carousel (lower numbers appear first)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='draft', max_length=10)),
                ('view_count', models.IntegerField(default=0, help_text='Number of times ad was displayed')),
                ('click_count', models.IntegerField(default=0, help_text='Number of times button was clicked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
