# Generated by Django 6.0 on 2025-12-07 00:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('reorder_level', models.IntegerField(default=10)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('is_publicly_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='prescriptions.medication')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_inventory',
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=30)),
                ('total_amount', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('insurance_covered', models.IntegerField(default=0)),
                ('delivery_method', models.CharField(default='pickup', max_length=50)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_fee', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ready_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_patient_orders', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_orders', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_orders', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'pharmacy_orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('dosage_form', models.CharField(blank=True, max_length=50)),
                ('strength', models.CharField(blank=True, max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacyinventory')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescriptions.medication')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.pharmacyorder')),
            ],
            options={
                'db_table': 'pharmacy_order_items',
            },
        ),
        migrations.CreateModel(
            name='PharmacyPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('received', 'Received'), ('partially_received', 'Partially Received'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_purchases',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyPurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_received', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescriptions.medication')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.pharmacypurchase')),
            ],
            options={
                'db_table': 'pharmacy_purchase_items',
            },
        ),
        migrations.CreateModel(
            name='PharmacySale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.IntegerField()),
                ('discount_amount', models.IntegerField(default=0)),
                ('tax_amount', models.IntegerField(default=0)),
                ('final_amount', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('change_given', models.IntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile_money', 'Mobile Money'), ('insurance', 'Insurance'), ('wallet', 'Wallet')], max_length=30)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sales_handled', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pharmacy.pharmacyorder')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_purchases', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacyinventory')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescriptions.medication')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.pharmacysale')),
            ],
            options={
                'db_table': 'pharmacy_sale_items',
            },
        ),
        migrations.CreateModel(
            name='PharmacyStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier'), ('inventory_clerk', 'Inventory Clerk'), ('delivery_person', 'Delivery Person')], max_length=30)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('can_manage_inventory', models.BooleanField(default=False)),
                ('can_process_orders', models.BooleanField(default=False)),
                ('can_handle_sales', models.BooleanField(default=False)),
                ('can_manage_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_employment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_staff',
            },
        ),
        migrations.CreateModel(
            name='PharmacySupplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_suppliers',
            },
        ),
        migrations.AddField(
            model_name='pharmacypurchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.pharmacysupplier'),
        ),
        migrations.CreateModel(
            name='DoctorPharmacyReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('was_fulfilled', models.BooleanField(default=False)),
                ('fulfillment_date', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.IntegerField(default=0)),
                ('bonus_earned', models.IntegerField(default=0)),
                ('bonus_paid', models.BooleanField(default=False)),
                ('bonus_paid_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_referrals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_referrals', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_referrals', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_referrals', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'doctor_pharmacy_referrals',
                'indexes': [models.Index(fields=['doctor', 'pharmacy'], name='doctor_phar_doctor__4a1359_idx'), models.Index(fields=['referral_date'], name='doctor_phar_referra_82b000_idx'), models.Index(fields=['was_fulfilled'], name='doctor_phar_was_ful_baa28d_idx'), models.Index(fields=['bonus_paid'], name='doctor_phar_bonus_p_a8ef2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PharmacyBonusConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bonus_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount'), ('tiered', 'Tiered')], default='percentage', max_length=30)),
                ('bonus_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fixed_bonus_amount', models.IntegerField(default=0)),
                ('min_prescriptions_per_month', models.IntegerField(default=0)),
                ('max_prescriptions_per_month', models.IntegerField(default=0)),
                ('bonus_amount_for_tier', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_bonus_configs', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_bonus_configs',
                'indexes': [models.Index(fields=['pharmacy', 'is_active'], name='pharmacy_bo_pharmac_fee4eb_idx'), models.Index(fields=['doctor'], name='pharmacy_bo_doctor__62c311_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pharmacyinventory',
            index=models.Index(fields=['pharmacy', 'medication'], name='pharmacy_in_pharmac_350695_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinventory',
            index=models.Index(fields=['expiry_date'], name='pharmacy_in_expiry__c0dde1_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinventory',
            index=models.Index(fields=['quantity_in_stock'], name='pharmacy_in_quantit_74893f_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinventory',
            index=models.Index(fields=['is_publicly_available'], name='pharmacy_in_is_publ_32b469_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyorder',
            index=models.Index(fields=['pharmacy', 'status'], name='pharmacy_or_pharmac_d18271_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyorder',
            index=models.Index(fields=['patient'], name='pharmacy_or_patient_4b4e55_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyorder',
            index=models.Index(fields=['order_number'], name='pharmacy_or_order_n_9e50c5_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyorder',
            index=models.Index(fields=['order_date'], name='pharmacy_or_order_d_3f14cf_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacysale',
            index=models.Index(fields=['pharmacy', 'sale_date'], name='pharmacy_sa_pharmac_2400f0_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacysale',
            index=models.Index(fields=['sale_number'], name='pharmacy_sa_sale_nu_473db8_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacystaff',
            index=models.Index(fields=['pharmacy', 'is_active'], name='pharmacy_st_pharmac_451bef_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacystaff',
            index=models.Index(fields=['email'], name='pharmacy_st_email_d072d1_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacysupplier',
            index=models.Index(fields=['pharmacy', 'is_active'], name='pharmacy_su_pharmac_942727_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacypurchase',
            index=models.Index(fields=['pharmacy', 'status'], name='pharmacy_pu_pharmac_50bdfc_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacypurchase',
            index=models.Index(fields=['supplier'], name='pharmacy_pu_supplie_e1706a_idx'),
        ),
    ]
