# Generated by Django 6.0 on 2025-12-14 12:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_rename_staff_fields_for_consistency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyStockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('adjustment', 'Ajustement'), ('return', 'Retour'), ('transfer', 'Transfert'), ('expired', 'Périmé'), ('damaged', 'Endommagé')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(choices=[('purchase', 'Réapprovisionnement'), ('sale', 'Vente'), ('correction', "Correction d'inventaire"), ('return_supplier', 'Retour fournisseur'), ('return_customer', 'Retour client'), ('transfer_in', 'Transfert entrant'), ('transfer_out', 'Transfert sortant'), ('expired', 'Produit expiré'), ('damaged', 'Produit endommagé'), ('theft', 'Vol'), ('loss', 'Perte'), ('donation', 'Don'), ('sample', 'Échantillon'), ('other', 'Autre')], max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='pharmacy.pharmacyinventory')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_movements', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_stock_movements',
                'ordering': ['-movement_date'],
                'indexes': [models.Index(fields=['pharmacy', 'movement_date'], name='pharmacy_st_pharmac_09e8a8_idx'), models.Index(fields=['inventory_item'], name='pharmacy_st_invento_f22688_idx'), models.Index(fields=['movement_type'], name='pharmacy_st_movemen_2739d4_idx')],
            },
        ),
    ]
