# Generated by Django 6.0 on 2025-12-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_pharmacystockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyorder',
            name='status',
            field=models.CharField(choices=[('cart', 'Shopping Cart'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
