# Generated by Django 6.0 on 2025-12-18 17:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_pharmacyorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('register_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('reconciled', 'Reconciled')], default='open', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_closing_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_mobile_money_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_insurance_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('number_of_transactions', models.IntegerField(default=0)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_registers', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_registers', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_registers',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='EndOfDaySettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settlement_number', models.CharField(max_length=50, unique=True)),
                ('settlement_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('approved', 'Approved'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost_of_goods', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mobile_money_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_claims', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('prescriptions_filled', models.IntegerField(default=0)),
                ('otc_sales', models.IntegerField(default=0)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('discrepancies', models.TextField(blank=True, help_text='Note any discrepancies found')),
                ('prepared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_settlements', to=settings.AUTH_USER_MODEL)),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eod_settlements', to='pharmacy.cashregister')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eod_settlements', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eod_settlements',
                'ordering': ['-settlement_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpiryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('30_days', '30 Days Before Expiry'), ('60_days', '60 Days Before Expiry'), ('90_days', '90 Days Before Expiry'), ('expired', 'Already Expired')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('expiry_date', models.DateField()),
                ('days_until_expiry', models.IntegerField()),
                ('quantity_affected', models.IntegerField()),
                ('estimated_loss_value', models.IntegerField(default=0, help_text='Potential financial loss if not sold')),
                ('alert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_expiry_alerts', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='pharmacy.pharmacyinventory')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expiry_alerts',
                'ordering': ['-alert_date'],
            },
        ),
        migrations.CreateModel(
            name='StockReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reconciliation_number', models.CharField(max_length=50, unique=True)),
                ('reconciliation_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_items_counted', models.IntegerField(default=0)),
                ('items_with_discrepancies', models.IntegerField(default=0)),
                ('total_variance_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_reconciliations',
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='StockReconciliationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_quantity', models.IntegerField(help_text='Quantity according to system')),
                ('counted_quantity', models.IntegerField(help_text='Actual physical count')),
                ('variance', models.IntegerField(help_text='Difference (counted - system)')),
                ('variance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unit_price', models.IntegerField()),
                ('variance_value', models.IntegerField(help_text='Financial impact of variance')),
                ('reason', models.CharField(blank=True, choices=[('theft', 'Theft/Loss'), ('damage', 'Damaged'), ('expired', 'Expired'), ('miscounted', 'Previous Miscount'), ('unreported_sale', 'Unreported Sale'), ('unreported_purchase', 'Unreported Purchase'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('counted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_items', to='pharmacy.pharmacyinventory')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.stockreconciliation')),
            ],
            options={
                'db_table': 'stock_reconciliation_items',
            },
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['pharmacy', 'status'], name='cash_regist_pharmac_e44c53_idx'),
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['opened_at'], name='cash_regist_opened__c51dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='endofdaysettlement',
            index=models.Index(fields=['pharmacy', 'settlement_date'], name='eod_settlem_pharmac_c868e9_idx'),
        ),
        migrations.AddIndex(
            model_name='endofdaysettlement',
            index=models.Index(fields=['status'], name='eod_settlem_status_45450c_idx'),
        ),
        migrations.AddIndex(
            model_name='expiryalert',
            index=models.Index(fields=['pharmacy', 'status'], name='expiry_aler_pharmac_114a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='expiryalert',
            index=models.Index(fields=['expiry_date'], name='expiry_aler_expiry__766c54_idx'),
        ),
        migrations.AddIndex(
            model_name='expiryalert',
            index=models.Index(fields=['alert_type'], name='expiry_aler_alert_t_61c0df_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreconciliation',
            index=models.Index(fields=['pharmacy', 'status'], name='stock_recon_pharmac_acb344_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreconciliation',
            index=models.Index(fields=['reconciliation_date'], name='stock_recon_reconci_f05108_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreconciliationitem',
            index=models.Index(fields=['reconciliation', 'inventory_item'], name='stock_recon_reconci_01a617_idx'),
        ),
    ]
