# Generated by Django 6.0 on 2025-12-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_add_inventory_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyorder',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code for this order', max_length=3),
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cash_on_delivery', 'Cash on Delivery'), ('card', 'Card'), ('mobile_money', 'Mobile Money'), ('insurance', 'Insurance'), ('wallet', 'Wallet')], default='cash_on_delivery', help_text='Payment method selected by patient', max_length=30),
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment transaction reference number', max_length=100),
        ),
    ]
