# Generated by Django 6.0 on 2025-12-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_add_payment_method_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cash_on_delivery', 'Cash on Delivery'), ('card', 'Card'), ('mobile_money', 'Mobile Money'), ('insurance', 'Insurance')], default='cash_on_delivery', help_text='Payment method selected by patient', max_length=30),
        ),
    ]
