# Generated by Django 6.0 on 2025-12-26 09:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_pharmacyinventory_created_by_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='doctorpharmacyreferral',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='doctorpharmacyreferral',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='doctorpharmacyreferral',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='doctorpharmacyreferral',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='doctorpharmacyreferral',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='doctorpharmacyreferral',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorpharmacyreferral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='doctorpharmacyreferral',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='endofdaysettlement',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='endofdaysettlement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='endofdaysettlement',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='endofdaysettlement',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='endofdaysettlement',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='endofdaysettlement',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='endofdaysettlement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='endofdaysettlement',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='pharmacybonusconfig',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='pharmacybonusconfig',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='pharmacybonusconfig',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='pharmacybonusconfig',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='pharmacybonusconfig',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='pharmacybonusconfig',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacybonusconfig',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='pharmacypurchase',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='pharmacypurchase',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='pharmacypurchase',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='pharmacypurchase',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='pharmacypurchase',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='pharmacypurchase',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacypurchase',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='pharmacypurchaseitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AddField(
            model_name='pharmacypurchaseitem',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='pharmacypurchaseitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='pharmacypurchaseitem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='pharmacypurchaseitem',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='pharmacypurchaseitem',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='pharmacypurchaseitem',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacypurchaseitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='pharmacypurchaseitem',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='pharmacystaff',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='pharmacystaff',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='pharmacystaff',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='pharmacystaff',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='pharmacystaff',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='pharmacystaff',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacystaff',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='pharmacysupplier',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='pharmacysupplier',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='pharmacysupplier',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='pharmacysupplier',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='pharmacysupplier',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='pharmacysupplier',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacysupplier',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='stockreconciliationitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AddField(
            model_name='stockreconciliationitem',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='stockreconciliationitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='stockreconciliationitem',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='stockreconciliationitem',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='stockreconciliationitem',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='stockreconciliationitem',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='stockreconciliationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='stockreconciliationitem',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='actual_closing_balance',
            field=models.IntegerField(blank=True, default=0, help_text='Actual closing balance in USD cents', null=True),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='expected_closing_balance',
            field=models.IntegerField(default=0, help_text='Expected closing balance in USD cents'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='opening_balance',
            field=models.IntegerField(default=0, help_text='Opening balance in USD cents'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='total_card_sales',
            field=models.IntegerField(default=0, help_text='Total card sales in USD cents'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='total_cash_sales',
            field=models.IntegerField(default=0, help_text='Total cash sales in USD cents'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='total_insurance_sales',
            field=models.IntegerField(default=0, help_text='Total insurance sales in USD cents'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='total_mobile_money_sales',
            field=models.IntegerField(default=0, help_text='Total mobile money sales in USD cents'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='variance',
            field=models.IntegerField(default=0, help_text='Variance in USD cents'),
        ),
        migrations.AlterField(
            model_name='doctorpharmacyreferral',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='doctorpharmacyreferral',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='card_sales',
            field=models.IntegerField(default=0, help_text='Card sales in USD cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='cash_sales',
            field=models.IntegerField(default=0, help_text='Cash sales in USD cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='cash_variance',
            field=models.IntegerField(default=0, help_text='Cash variance in USD cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='closing_cash',
            field=models.IntegerField(default=0, help_text='Closing cash in USD cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='gross_profit',
            field=models.IntegerField(default=0, help_text='Gross profit in USD cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='insurance_claims',
            field=models.IntegerField(default=0, help_text='Insurance claims in USD cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='mobile_money_sales',
            field=models.IntegerField(default=0, help_text='Mobile money sales in USD cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='opening_cash',
            field=models.IntegerField(default=0, help_text='Opening cash in USD cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='total_cost_of_goods',
            field=models.IntegerField(default=0, help_text='Total COGS in USD cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='total_revenue',
            field=models.IntegerField(default=0, help_text='Total revenue in USD cents'),
        ),
        migrations.AlterField(
            model_name='expiryalert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='expiryalert',
            name='estimated_loss_value',
            field=models.IntegerField(default=0, help_text='Potential financial loss if not sold in USD cents'),
        ),
        migrations.AlterField(
            model_name='expiryalert',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacybonusconfig',
            name='bonus_amount_for_tier',
            field=models.IntegerField(default=0, help_text='Tier bonus amount in USD cents'),
        ),
        migrations.AlterField(
            model_name='pharmacybonusconfig',
            name='bonus_percentage',
            field=models.IntegerField(default=0, help_text='Bonus percentage in basis points (e.g., 500 = 5%)'),
        ),
        migrations.AlterField(
            model_name='pharmacybonusconfig',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='pharmacybonusconfig',
            name='fixed_bonus_amount',
            field=models.IntegerField(default=0, help_text='Fixed bonus amount in USD cents'),
        ),
        migrations.AlterField(
            model_name='pharmacybonusconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacybonusconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='pharmacypurchase',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='pharmacypurchase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacypurchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='pharmacypurchaseitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacystaff',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='pharmacystaff',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacystaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='pharmacysupplier',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='pharmacysupplier',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacysupplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='stockreconciliation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='stockreconciliation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockreconciliation',
            name='total_variance_value',
            field=models.IntegerField(default=0, help_text='Total variance value in USD cents'),
        ),
        migrations.AlterField(
            model_name='stockreconciliation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='stockreconciliationitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockreconciliationitem',
            name='unit_price',
            field=models.IntegerField(help_text='Unit price in USD cents'),
        ),
        migrations.AlterField(
            model_name='stockreconciliationitem',
            name='variance_percentage',
            field=models.IntegerField(default=0, help_text='Variance percentage in basis points (e.g., 1000 = 10%)'),
        ),
        migrations.AlterField(
            model_name='stockreconciliationitem',
            name='variance_value',
            field=models.IntegerField(help_text='Financial impact of variance in USD cents'),
        ),
    ]
