# Generated by Django 6.0 on 2025-12-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_cashregister_created_by_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacysale',
            name='payment_method',
            field=models.CharField(choices=[('fedapay_mobile', 'FedaPay Mobile Money'), ('fedapay_card', 'FedaPay Card'), ('mtn_momo', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('orange_money', 'Orange Money'), ('onsite_cash', 'On-site Cash'), ('insurance', 'Insurance')], max_length=30),
        ),
    ]
