# Generated by Django 6.0 on 2025-12-27 00:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_remove_wallet_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True)),
                ('created_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True)),
                ('modified_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('counter_number', models.CharField(max_length=50)),
                ('counter_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('current_session_started', models.DateTimeField(blank=True, null=True)),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter', to='pharmacy.cashregister')),
                ('current_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_counter', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_counters',
            },
        ),
        migrations.CreateModel(
            name='OrderQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True)),
                ('created_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True)),
                ('modified_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed by Staff'), ('preparing', 'Preparing Medications'), ('ready', 'Ready for Pickup/Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('queue_number', models.IntegerField()),
                ('priority', models.IntegerField(default=0, help_text='Higher priority processed first')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_ready_time', models.DateTimeField(blank=True, null=True)),
                ('actual_ready_time', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.CharField(help_text='QR code for pickup verification', max_length=100, unique=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_status', to='pharmacy.pharmacyorder')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_queues', to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to='pharmacy.pharmacycounter')),
            ],
            options={
                'db_table': 'order_queue',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True)),
                ('created_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True)),
                ('modified_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('qr_code', models.CharField(max_length=100, unique=True)),
                ('verification_code', models.CharField(help_text='Backup verification code', max_length=10)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('payment_completed', models.BooleanField(default=False)),
                ('payment_transaction_ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_verifications', to='pharmacy.pharmacycounter')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_verification', to='pharmacy.pharmacyorder')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_verifications', to=settings.AUTH_USER_MODEL)),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pickups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pickup_verifications',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True)),
                ('created_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True)),
                ('modified_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned to Delivery Person'), ('picked_up', 'Picked Up from Pharmacy'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Destination'), ('delivered', 'Delivered & Confirmed'), ('failed', 'Delivery Failed'), ('returned', 'Returned to Pharmacy')], default='pending', max_length=30)),
                ('delivery_address', models.TextField()),
                ('delivery_phone', models.CharField(max_length=20)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('patient_confirmation_code', models.CharField(help_text='Code patient provides to confirm delivery', max_length=10)),
                ('confirmed_by_patient', models.BooleanField(default=False)),
                ('confirmation_time', models.DateTimeField(blank=True, null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('failed_reason', models.TextField(blank=True)),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='delivery_photos/')),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_assigned', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tracking', to='pharmacy.pharmacyorder')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_tracking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pharmacy', 'status'], name='delivery_tr_pharmac_b4147a_idx'), models.Index(fields=['tracking_number'], name='delivery_tr_trackin_30f4f7_idx'), models.Index(fields=['delivery_person', 'status'], name='delivery_tr_deliver_eda1ae_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pharmacycounter',
            index=models.Index(fields=['pharmacy', 'is_active'], name='pharmacy_co_pharmac_fc2cff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacycounter',
            unique_together={('pharmacy', 'counter_number')},
        ),
        migrations.AddIndex(
            model_name='orderqueue',
            index=models.Index(fields=['pharmacy', 'status'], name='order_queue_pharmac_f085be_idx'),
        ),
        migrations.AddIndex(
            model_name='orderqueue',
            index=models.Index(fields=['queue_number'], name='order_queue_queue_n_823cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='orderqueue',
            index=models.Index(fields=['qr_code'], name='order_queue_qr_code_1f8ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='pickupverification',
            index=models.Index(fields=['pharmacy', 'scanned_at'], name='pickup_veri_pharmac_dc3b87_idx'),
        ),
        migrations.AddIndex(
            model_name='pickupverification',
            index=models.Index(fields=['qr_code'], name='pickup_veri_qr_code_12a386_idx'),
        ),
    ]
