# Generated by Django 6.0 on 2025-12-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_add_multi_counter_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='actual_closing_balance',
            field=models.IntegerField(blank=True, default=0, help_text='Actual closing balance in XOF cents', null=True),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='expected_closing_balance',
            field=models.IntegerField(default=0, help_text='Expected closing balance in XOF cents'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='opening_balance',
            field=models.IntegerField(default=0, help_text='Opening balance in XOF cents'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='total_card_sales',
            field=models.IntegerField(default=0, help_text='Total card sales in XOF cents'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='total_cash_sales',
            field=models.IntegerField(default=0, help_text='Total cash sales in XOF cents'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='total_insurance_sales',
            field=models.IntegerField(default=0, help_text='Total insurance sales in XOF cents'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='total_mobile_money_sales',
            field=models.IntegerField(default=0, help_text='Total mobile money sales in XOF cents'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='variance',
            field=models.IntegerField(default=0, help_text='Variance in XOF cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='card_sales',
            field=models.IntegerField(default=0, help_text='Card sales in XOF cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='cash_sales',
            field=models.IntegerField(default=0, help_text='Cash sales in XOF cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='cash_variance',
            field=models.IntegerField(default=0, help_text='Cash variance in XOF cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='closing_cash',
            field=models.IntegerField(default=0, help_text='Closing cash in XOF cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='gross_profit',
            field=models.IntegerField(default=0, help_text='Gross profit in XOF cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='insurance_claims',
            field=models.IntegerField(default=0, help_text='Insurance claims in XOF cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='mobile_money_sales',
            field=models.IntegerField(default=0, help_text='Mobile money sales in XOF cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='opening_cash',
            field=models.IntegerField(default=0, help_text='Opening cash in XOF cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='total_cost_of_goods',
            field=models.IntegerField(default=0, help_text='Total COGS in XOF cents'),
        ),
        migrations.AlterField(
            model_name='endofdaysettlement',
            name='total_revenue',
            field=models.IntegerField(default=0, help_text='Total revenue in XOF cents'),
        ),
        migrations.AlterField(
            model_name='expiryalert',
            name='estimated_loss_value',
            field=models.IntegerField(default=0, help_text='Potential financial loss if not sold in XOF cents'),
        ),
        migrations.AlterField(
            model_name='pharmacybonusconfig',
            name='bonus_amount_for_tier',
            field=models.IntegerField(default=0, help_text='Tier bonus amount in XOF cents'),
        ),
        migrations.AlterField(
            model_name='pharmacybonusconfig',
            name='fixed_bonus_amount',
            field=models.IntegerField(default=0, help_text='Fixed bonus amount in XOF cents'),
        ),
        migrations.AlterField(
            model_name='pharmacyorder',
            name='currency',
            field=models.CharField(default='XOF', help_text='Currency code for this order', max_length=3),
        ),
        migrations.AlterField(
            model_name='stockreconciliation',
            name='total_variance_value',
            field=models.IntegerField(default=0, help_text='Total variance value in XOF cents'),
        ),
        migrations.AlterField(
            model_name='stockreconciliationitem',
            name='unit_price',
            field=models.IntegerField(help_text='Unit price in XOF cents'),
        ),
        migrations.AlterField(
            model_name='stockreconciliationitem',
            name='variance_value',
            field=models.IntegerField(help_text='Financial impact of variance in XOF cents'),
        ),
    ]
