# Generated by Django 6.0 on 2025-12-31 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_alter_cashregister_actual_closing_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('consultation_fee', models.IntegerField(default=0)),
                ('has_delivery', models.BooleanField(default=False)),
                ('delivery_radius_km', models.IntegerField(default=0)),
                ('accepts_prescriptions', models.BooleanField(default=True)),
                ('has_refrigeration', models.BooleanField(default=False)),
                ('operates_24_7', models.BooleanField(default=False)),
                ('operating_hours', models.JSONField(default=dict)),
                ('services_offered', models.JSONField(default=list)),
                ('rating', models.FloatField(default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_data',
            },
        ),
    ]
