# Generated by Django 6.0 on 2026-01-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_add_syncmixin_to_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyinventory',
            name='region_code',
        ),
    ]
