# Generated by Django 6.0 on 2026-01-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0018_add_identifier_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacydata',
            name='activation_code',
            field=models.CharField(blank=True, help_text='12-digit activation code for local instance', max_length=14),
        ),
    ]
