# Generated by Django 6.0 on 2025-12-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_bankaccount_created_by_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
