# Generated by Django 6.0 on 2025-12-19 13:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_legalrepresentative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('job_title', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern'), ('temporary', 'Temporary')], max_length=20)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('salary_type', models.CharField(choices=[('monthly', 'Monthly'), ('hourly', 'Hourly'), ('daily', 'Daily')], max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('tax_identification_number', models.CharField(blank=True, max_length=50)),
                ('social_security_number', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department')),
                ('organization', models.ForeignKey(help_text='The employer (Hospital/Pharmacy/Insurance Company)', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text="The employee's participant account", on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_employee',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('benefit_type', models.CharField(choices=[('health_insurance', 'Health Insurance'), ('life_insurance', 'Life Insurance'), ('pension', 'Pension Plan'), ('transportation', 'Transportation Allowance'), ('housing', 'Housing Allowance'), ('meal', 'Meal Allowance'), ('education', 'Education Assistance'), ('other', 'Other')], max_length=30)),
                ('benefit_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider_name', models.CharField(blank=True, max_length=255)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_employee_benefit',
                'ordering': ['employee', 'benefit_type'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('days_per_year', models.IntegerField(help_text='Number of days entitled per year')),
                ('max_carryover_days', models.IntegerField(default=0, help_text='Maximum days that can be carried over to next year')),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_documentation', models.BooleanField(default=False, help_text='Requires supporting documents (e.g., medical certificate)')),
                ('requires_approval', models.BooleanField(default=True)),
                ('minimum_notice_days', models.IntegerField(default=0, help_text='Minimum days of notice required before leave start')),
                ('maximum_consecutive_days', models.IntegerField(blank=True, help_text='Maximum consecutive days allowed', null=True)),
                ('requires_minimum_service_months', models.IntegerField(default=0, help_text='Minimum months of service required to be eligible')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_leave_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=1, help_text='Can include half days (e.g., 2.5 days)', max_digits=5)),
                ('reason', models.TextField()),
                ('attachment_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('handover_notes', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee')),
                ('handover_to', models.ForeignKey(blank=True, help_text='Employee handling duties during absence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_requests', to='hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='hr.leavetype')),
            ],
            options={
                'db_table': 'hr_leave_request',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('entitled_days', models.DecimalField(decimal_places=1, help_text='Total days entitled for the year', max_digits=5)),
                ('carried_over_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Days carried over from previous year', max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('pending_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Days in pending leave requests', max_digits=5)),
                ('remaining_days', models.DecimalField(decimal_places=1, help_text='Available days remaining', max_digits=5)),
                ('adjustment_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Manual adjustments (positive or negative)', max_digits=5)),
                ('adjustment_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_balances', to='hr.leavetype')),
            ],
            options={
                'db_table': 'hr_leave_balance',
                'ordering': ['-year', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_name', models.CharField(help_text='e.g., January 2025 Payroll', max_length=100)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('semi_monthly', 'Semi-Monthly'), ('monthly', 'Monthly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pay_date', models.DateField(help_text='Actual payment date')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('open', 'Open'), ('processing', 'Processing'), ('processed', 'Processed'), ('paid', 'Paid'), ('closed', 'Closed')], default='scheduled', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_payroll_period',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('base_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Housing, transport, etc.', max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Bank transfer, cash, mobile money, etc.', max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='hr.employee')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='hr.payrollperiod')),
            ],
            options={
                'db_table': 'hr_payroll_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deduction_type', models.CharField(choices=[('income_tax', 'Income Tax'), ('social_security', 'Social Security'), ('pension', 'Pension Contribution'), ('health_insurance', 'Health Insurance'), ('loan_repayment', 'Loan Repayment'), ('advance_repayment', 'Advance Repayment'), ('union_dues', 'Union Dues'), ('garnishment', 'Garnishment'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='hr.payrollrun')),
            ],
            options={
                'db_table': 'hr_payroll_deduction',
                'ordering': ['deduction_type'],
            },
        ),
        migrations.CreateModel(
            name='TimeAndAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('break_duration_minutes', models.IntegerField(default=0, help_text='Total break time in minutes')),
                ('clock_in_location', models.CharField(blank=True, max_length=255)),
                ('clock_out_location', models.CharField(blank=True, max_length=255)),
                ('clock_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('clock_out_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('is_early_departure', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_time_attendance',
                'ordering': ['-clock_in'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'status'], name='hr_employee_organiz_10e2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='hr_employee_employe_ec40c6_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date'], name='hr_employee_hire_da_4d71d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('organization', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status'], name='hr_leave_re_employe_5480af_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='hr_leave_re_start_d_07740e_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status'], name='hr_leave_re_status_130c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['employee', 'year'], name='hr_leave_ba_employe_dc8e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['year'], name='hr_leave_ba_year_dc806b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'year')},
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['organization', 'status'], name='hr_payroll__organiz_4a3d95_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='hr_payroll__start_d_3b4dfa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together={('organization', 'period_name')},
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['payroll_period', 'payment_status'], name='hr_payroll__payroll_a1aa8c_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['employee', 'payment_status'], name='hr_payroll__employe_5cef4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('payroll_period', 'employee')},
        ),
        migrations.AddIndex(
            model_name='timeandattendance',
            index=models.Index(fields=['employee', 'clock_in'], name='hr_time_att_employe_c67a64_idx'),
        ),
        migrations.AddIndex(
            model_name='timeandattendance',
            index=models.Index(fields=['clock_in'], name='hr_time_att_clock_i_db5f52_idx'),
        ),
    ]
