# Generated by Django 6.0 on 2025-12-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_created_by_instance_employee_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
