# Generated by Django 6.0 on 2025-12-24 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=100)),
                ('object_id', models.UUIDField()),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_code_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'qrcode_generator_qrcodes',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='qrcode_gene_content_19cb19_idx'), models.Index(fields=['created_at'], name='qrcode_gene_created_bf9353_idx')],
            },
        ),
    ]
