# Generated by Django 6.0 on 2025-12-07 00:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIHealthInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('recommendation', 'Recommendation'), ('warning', 'Warning'), ('trend', 'Trend'), ('prediction', 'Prediction'), ('analysis', 'Analysis')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('data_points_used', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_read', models.BooleanField(default=False)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_health_insights',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('prescription', 'Prescription'), ('medical_record', 'Medical Record'), ('insurance_document', 'Insurance Document'), ('lab_result', 'Lab Result'), ('imaging', 'Imaging'), ('id_card', 'ID Card'), ('other', 'Other')], max_length=50)),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MenstrualCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_start_date', models.DateField()),
                ('cycle_end_date', models.DateField(blank=True, null=True)),
                ('period_length', models.IntegerField(default=5)),
                ('cycle_length', models.IntegerField(default=28)),
                ('flow_intensity', models.CharField(blank=True, max_length=20)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('predicted_ovulation_date', models.DateField(blank=True, null=True)),
                ('predicted_next_period_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menstrual_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menstrual_cycles',
                'ordering': ['-cycle_start_date'],
            },
        ),
        migrations.CreateModel(
            name='TelemedicineSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('room_id', models.CharField(max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('scheduled_start_time', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('recording_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemedicine_session', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_sessions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telemedicine_sessions',
                'ordering': ['-scheduled_start_time'],
            },
        ),
        migrations.CreateModel(
            name='WearableDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('smartwatch', 'Smartwatch'), ('fitness_tracker', 'Fitness Tracker'), ('smart_ring', 'Smart Ring'), ('blood_pressure_monitor', 'Blood Pressure Monitor'), ('glucose_monitor', 'Glucose Monitor')], max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('paired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wearable_devices',
            },
        ),
        migrations.CreateModel(
            name='WearableData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=50)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('blood_oxygen', models.FloatField(blank=True, null=True)),
                ('stress_level', models.IntegerField(blank=True, null=True)),
                ('sleep_duration', models.IntegerField(blank=True, null=True)),
                ('sleep_quality', models.CharField(blank=True, max_length=50)),
                ('deep_sleep', models.IntegerField(blank=True, null=True)),
                ('light_sleep', models.IntegerField(blank=True, null=True)),
                ('rem_sleep', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_data', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='health_records.wearabledevice')),
            ],
            options={
                'db_table': 'wearable_data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participants', models.JSONField(default=list)),
                ('type', models.CharField(choices=[('lab_result', 'Lab Result'), ('prescription', 'Prescription'), ('diagnosis', 'Diagnosis'), ('imaging', 'Imaging'), ('vaccination', 'Vaccination'), ('allergy', 'Allergy'), ('surgery', 'Surgery'), ('visit_summary', 'Visit Summary'), ('referral', 'Referral'), ('discharge_summary', 'Discharge Summary')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('diagnosis', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('is_patient_uploaded', models.BooleanField(default=False)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('encrypted_data', models.TextField(blank=True)),
                ('date_of_record', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_records',
                'ordering': ['-date_of_record'],
                'indexes': [models.Index(fields=['assigned_to', 'type'], name='health_reco_assigne_274c3d_idx'), models.Index(fields=['created_by'], name='health_reco_created_7788a2_idx'), models.Index(fields=['date_of_record'], name='health_reco_date_of_9a4b5e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wearabledevice',
            index=models.Index(fields=['patient', 'status'], name='wearable_de_patient_9c5fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='wearabledevice',
            index=models.Index(fields=['device_id'], name='wearable_de_device__f9dc71_idx'),
        ),
        migrations.AddIndex(
            model_name='wearabledata',
            index=models.Index(fields=['patient', 'timestamp'], name='wearable_da_patient_e59838_idx'),
        ),
        migrations.AddIndex(
            model_name='wearabledata',
            index=models.Index(fields=['device', 'timestamp'], name='wearable_da_device__a96a61_idx'),
        ),
    ]
