# Generated by Django 6.0 on 2025-12-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIHealthInsight',
        ),
    ]
