# Generated by Django 6.0 on 2026-01-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0004_alter_documentupload_created_by_instance_and_more'),
    ]

    operations = [
        # Just remove model from Django state, don't touch the database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='MenstrualCycle',
                ),
            ],
            # Don't delete the table in database
            database_operations=[],
        ),
    ]
