# Generated by Django 6.0 on 2026-01-03 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0005_remove_menstrual_cycle'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wearabledata',
            name='wearable_da_patient_e59838_idx',
        ),
        migrations.RemoveIndex(
            model_name='wearabledata',
            name='wearable_da_device__a96a61_idx',
        ),
        migrations.RemoveIndex(
            model_name='wearabledevice',
            name='wearable_de_patient_9c5fd5_idx',
        ),
        migrations.RemoveIndex(
            model_name='wearabledevice',
            name='wearable_de_device__f9dc71_idx',
        ),
        migrations.RemoveField(
            model_name='wearabledevice',
            name='patient',
        ),
        migrations.DeleteModel(
            name='WearableData',
        ),
        migrations.DeleteModel(
            name='WearableDevice',
        ),
    ]
