# Generated by Django 6.0 on 2026-01-03 18:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0006_remove_wearabledata_wearable_da_patient_e59838_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True)),
                ('created_by_instance', models.UUIDField(blank=True, default=uuid.uuid4, help_text='UUID of instance that created this record')),
                ('modified_by_instance', models.UUIDField(blank=True, default=uuid.uuid4, help_text='UUID of instance that last modified this record')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True)),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('download', 'View & Download'), ('edit', 'View, Download & Edit')], default='view', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message to recipient')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this share expires', null=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_at', models.DateTimeField(blank=True, help_text='When recipient first accessed', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document_shares',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.AddField(
            model_name='documentupload',
            name='is_shareable',
            field=models.BooleanField(default=True, help_text='Can this document be shared?'),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='share_count',
            field=models.IntegerField(default=0, help_text='Number of times shared'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['uploaded_by', 'status'], name='document_up_uploade_bb857c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['document_type'], name='document_up_documen_0966cb_idx'),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='health_records.documentupload'),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['shared_by', 'status'], name='document_sh_shared__21b0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['shared_with', 'status'], name='document_sh_shared__3d1c02_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['expires_at'], name='document_sh_expires_a17740_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentshare',
            unique_together={('document', 'shared_with')},
        ),
    ]
