# Generated by Django 6.0 on 2026-01-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0007_documentshare_documentupload_is_shareable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, help_text='Diastolic BP in mmHg', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, help_text='Systolic BP in mmHg', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='heart_rate',
            field=models.IntegerField(blank=True, help_text='Heart rate in bpm', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in °C', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
