# Generated by Django 6.0 on 2025-12-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('is_supported', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'currency_pairs',
                'unique_together': {('base_currency', 'quote_currency')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(choices=[('API', 'External API'), ('MANUAL', 'Manual Entry'), ('STATIC', 'Static Fallback')], default='STATIC', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'currency_exchange_rates',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', '-fetched_at'], name='currency_ex_from_cu_ab56ae_idx'), models.Index(fields=['is_active', '-fetched_at'], name='currency_ex_is_acti_78adc5_idx')],
            },
        ),
    ]
