# Generated by Django 6.0 on 2025-12-27 00:06

import django.utils.timezone
import uuid
from django.db import migrations, models


def migrate_to_uuid_id(apps, schema_editor):
    """
    Custom migration to convert bigint IDs to UUIDs
    Since PostgreSQL cannot cast bigint to UUID, we need to:
    1. Add a new UUID column (temp_uuid_id)
    2. Generate UUIDs for all existing records
    3. Drop old id column
    4. Rename temp_uuid_id to id
    """
    # This will be done in SQL operations below


class Migration(migrations.Migration):

    dependencies = [
        ('currency_converter', '0001_initial'),
    ]

    operations = [
        # Step 1: Add all SyncMixin fields first
        migrations.AddField(
            model_name='currencypair',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AddField(
            model_name='currencypair',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='currencypair',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='currencypair',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='currencypair',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='currencypair',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='currencypair',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='currencypair',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='currencypair',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='created_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='region_code',
            field=models.CharField(db_index=True, default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for conflict detection'),
        ),
        
        # Step 2: Convert ID from bigint to UUID using raw SQL
        # For CurrencyPair
        migrations.RunSQL(
            # Forward SQL - Convert to UUID
            sql="""
                -- Add temp UUID column
                ALTER TABLE currency_pairs ADD COLUMN temp_uuid_id UUID DEFAULT gen_random_uuid();
                
                -- Drop old constraints and indexes referencing old id
                ALTER TABLE currency_pairs DROP CONSTRAINT IF EXISTS currency_pairs_pkey CASCADE;
                
                -- Drop old id column
                ALTER TABLE currency_pairs DROP COLUMN id;
                
                -- Rename temp to id
                ALTER TABLE currency_pairs RENAME COLUMN temp_uuid_id TO id;
                
                -- Add primary key constraint
                ALTER TABLE currency_pairs ADD PRIMARY KEY (id);
            """,
            # Reverse SQL - Not safe, but required by Django
            reverse_sql="""
                -- Cannot safely reverse UUID to bigint - would lose data
                -- This is a one-way migration
                SELECT 1;
            """
        ),
        
        # For ExchangeRate
        migrations.RunSQL(
            # Forward SQL - Convert to UUID
            sql="""
                -- Add temp UUID column
                ALTER TABLE currency_exchange_rates ADD COLUMN temp_uuid_id UUID DEFAULT gen_random_uuid();
                
                -- Drop old constraints and indexes referencing old id
                ALTER TABLE currency_exchange_rates DROP CONSTRAINT IF EXISTS currency_exchange_rates_pkey CASCADE;
                
                -- Drop old id column
                ALTER TABLE currency_exchange_rates DROP COLUMN id;
                
                -- Rename temp to id
                ALTER TABLE currency_exchange_rates RENAME COLUMN temp_uuid_id TO id;
                
                -- Add primary key constraint
                ALTER TABLE currency_exchange_rates ADD PRIMARY KEY (id);
            """,
            # Reverse SQL - Not safe, but required by Django
            reverse_sql="""
                -- Cannot safely reverse UUID to bigint - would lose data
                -- This is a one-way migration
                SELECT 1;
            """
        ),
    ]
