# Generated by Django 6.0 on 2025-12-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_converter', '0003_alter_currencypair_id_alter_exchangerate_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='currency_ex_from_cu_ab56ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='currency_ex_is_acti_78adc5_idx',
        ),
        # First add new fields
        migrations.AddField(
            model_name='exchangerate',
            name='base_code',
            field=models.CharField(db_index=True, default='XOF', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='target_code',
            field=models.CharField(db_index=True, default='XOF', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='time_last_update_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Now update unique_together with new fields
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('base_code', 'target_code', 'fetched_at')},
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='fetched_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(choices=[('API', 'External API'), ('MANUAL', 'Manual Entry'), ('STATIC', 'Static Fallback')], db_index=True, default='API', max_length=20),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['base_code', 'target_code', '-fetched_at'], name='currency_ex_base_co_f1fe61_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['is_active', 'source', '-fetched_at'], name='currency_ex_is_acti_5aaa84_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['base_code', 'is_active'], name='currency_ex_base_co_576a86_idx'),
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='from_currency',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='to_currency',
        ),
    ]
