# Generated by Django 6.0 on 2025-12-31 17:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_converter', '0004_remove_exchangerate_currency_ex_from_cu_ab56ae_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True)),
                ('created_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True)),
                ('modified_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True)),
                ('transaction_id', models.UUIDField(db_index=True, help_text='UUID of related transaction')),
                ('conversion_type', models.CharField(choices=[('transaction', 'Transaction Payment'), ('appointment', 'Appointment Booking'), ('prescription', 'Prescription Fulfillment'), ('service', 'Service Payment'), ('payout', 'Provider Payout'), ('refund', 'Refund Processing'), ('other', 'Other')], default='transaction', max_length=20)),
                ('from_currency', models.CharField(db_index=True, help_text='Source currency code', max_length=3)),
                ('to_currency', models.CharField(db_index=True, help_text='Target currency code', max_length=3)),
                ('from_amount', models.DecimalField(decimal_places=2, help_text='Amount in source currency', max_digits=18)),
                ('to_amount', models.DecimalField(decimal_places=2, help_text='Amount in target currency', max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=8, help_text='Exchange rate used', max_digits=18)),
                ('participant_country', models.CharField(blank=True, help_text='ISO country code from phone/geo', max_length=3)),
                ('participant_phone_country', models.CharField(blank=True, help_text='Country from phone number', max_length=3)),
                ('resolved_via', models.CharField(choices=[('phone', 'Phone Number'), ('geo', 'Geolocation'), ('combined', 'Phone + Geo'), ('default', 'Default')], default='default', help_text='How currency was determined', max_length=20)),
                ('rate_source', models.CharField(choices=[('database', 'Database'), ('api', 'API'), ('static', 'Static Fallback')], default='database', help_text='Source of exchange rate', max_length=20)),
                ('rate_fetched_at', models.DateTimeField(blank=True, help_text='When rate was fetched', null=True)),
                ('converted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When conversion happened')),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('participant', models.ForeignKey(help_text='Participant whose currency was converted', on_delete=django.db.models.deletion.CASCADE, related_name='currency_conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'currency_conversion_logs',
                'ordering': ['-converted_at'],
                'indexes': [models.Index(fields=['transaction_id', '-converted_at'], name='currency_co_transac_aa403c_idx'), models.Index(fields=['participant', '-converted_at'], name='currency_co_partici_14d63d_idx'), models.Index(fields=['from_currency', 'to_currency', '-converted_at'], name='currency_co_from_cu_406ab2_idx'), models.Index(fields=['conversion_type', '-converted_at'], name='currency_co_convers_542753_idx'), models.Index(fields=['resolved_via', '-converted_at'], name='currency_co_resolve_1ceee9_idx')],
            },
        ),
    ]
