# Generated by Django 6.0 on 2025-12-07 00:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('is_controlled_substance', models.BooleanField(default=False)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('side_effects', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('dosage_forms', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medications',
                'indexes': [models.Index(fields=['name'], name='medications_name_906f5e_idx'), models.Index(fields=['generic_name'], name='medications_generic_f22126_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('issue_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pendingRenewal', 'Pending Renewal'), ('renewed', 'Renewed'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('ordered', 'Ordered'), ('fulfilled', 'Fulfilled'), ('partiallyFulfilled', 'Partially Fulfilled'), ('verified', 'Verified'), ('transferred', 'Transferred'), ('suspended', 'Suspended')], default='active', max_length=30)),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('controlled', 'Controlled'), ('emergency', 'Emergency'), ('repeat', 'Repeat'), ('acute', 'Acute'), ('chronic', 'Chronic'), ('telemedicine', 'Telemedicine')], default='regular', max_length=30)),
                ('diagnosis', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('max_refills', models.IntegerField(default=0)),
                ('refills_used', models.IntegerField(default=0)),
                ('refill_status', models.CharField(choices=[('none', 'None'), ('available', 'Available'), ('exhausted', 'Exhausted'), ('pending_approval', 'Pending Approval')], default='none', max_length=30)),
                ('is_controlled_substance', models.BooleanField(default=False)),
                ('requires_pharmacist_verification', models.BooleanField(default=False)),
                ('drug_interaction_warnings', models.JSONField(blank=True, default=list)),
                ('allergy_warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('preferred_pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionFulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('partially_completed', 'Partially Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('fulfillment_date', models.DateTimeField(blank=True, null=True)),
                ('total_cost', models.IntegerField(default=0)),
                ('patient_paid', models.IntegerField(default=0)),
                ('insurance_covered', models.IntegerField(default=0)),
                ('pharmacist_signature', models.CharField(blank=True, max_length=255)),
                ('patient_signature', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_fulfillments', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescription_fulfillments',
                'ordering': ['-fulfillment_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('frequency', models.CharField(choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily'), ('three_times_daily', 'Three Times Daily'), ('four_times_daily', 'Four Times Daily'), ('every_6_hours', 'Every 6 Hours'), ('every_8_hours', 'Every 8 Hours'), ('every_12_hours', 'Every 12 Hours'), ('as_needed', 'As Needed')], max_length=50)),
                ('duration_days', models.IntegerField()),
                ('instructions', models.TextField(blank=True)),
                ('route', models.CharField(blank=True, max_length=50)),
                ('timing', models.CharField(blank=True, max_length=100)),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prescriptions.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescription_items',
            },
        ),
        migrations.CreateModel(
            name='FulfillmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_fulfilled', models.IntegerField()),
                ('quantity_remaining', models.IntegerField(default=0)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_price', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescriptionfulfillment')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_items', to='prescriptions.prescriptionitem')),
            ],
            options={
                'db_table': 'fulfillment_items',
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='prescriptio_patient_e097dd_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor'], name='prescriptio_doctor__f3c41d_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['issue_date'], name='prescriptio_issue_d_12fd48_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['valid_until'], name='prescriptio_valid_u_926374_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['region_code', 'status'], name='prescriptio_region__50a0b4_idx'),
        ),
    ]
