# Generated by Django 6.0 on 2025-12-24 21:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRenewalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=30)),
                ('patient_notes', models.TextField(blank=True, help_text="Patient's reason for renewal request")),
                ('doctor_notes', models.TextField(blank=True, help_text="Doctor's response or notes")),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_renewal_requests', to=settings.AUTH_USER_MODEL)),
                ('original_prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to='prescriptions.prescription')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_renewal_requests', to=settings.AUTH_USER_MODEL)),
                ('renewed_prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from_request', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescription_renewal_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='prescriptio_patient_ddebdf_idx'), models.Index(fields=['doctor', 'status'], name='prescriptio_doctor__fa7e6e_idx'), models.Index(fields=['original_prescription'], name='prescriptio_origina_d3b8fa_idx')],
            },
        ),
    ]
