# Generated by Django 6.0 on 2025-12-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_fulfillmentitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Client-provided unique key to prevent duplicate prescription creation', max_length=255, null=True, unique=True),
        ),
    ]
