# Generated by Django 6.0 on 2026-01-02 20:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_add_syncmixin_to_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
