# Generated by Django 6.0 on 2026-01-03 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0008_healthrecord_blood_pressure_diastolic_and_more'),
        ('prescriptions', '0007_prescription_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='health_record',
            field=models.ForeignKey(blank=True, help_text='Link to the medical consultation/record that generated this prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='health_records.healthrecord'),
        ),
    ]
