# Generated by Django 6.0 on 2026-01-01 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_dependentprofile_created_by_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentprofile',
            name='created_by_instance',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='UUID of instance that created this record'),
        ),
        migrations.AlterField(
            model_name='dependentprofile',
            name='modified_by_instance',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='UUID of instance that last modified this record'),
        ),
    ]
