# Generated by Django 6.0 on 2026-01-02 21:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_add_syncmixin_to_dependentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='alcohol_consumption',
            field=models.CharField(blank=True, choices=[('none', 'Aucun'), ('occasional', 'Occasionnel'), ('moderate', 'Modéré'), ('heavy', 'Important')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='last_checkup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='last_dental_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='last_eye_exam',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='last_gynecological_exam',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='last_mammogram',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='physical_activity',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sédentaire'), ('light', 'Léger'), ('moderate', 'Modéré'), ('active', 'Actif')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('former', 'Ancien fumeur'), ('current', 'Fumeur actuel')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='vaccination_records',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='PersonalHealthNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True)),
                ('created_by_instance', models.UUIDField(blank=True, default=uuid.uuid4, help_text='UUID of instance that created this record')),
                ('modified_by_instance', models.UUIDField(blank=True, default=uuid.uuid4, help_text='UUID of instance that last modified this record')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('note_date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('symptom', 'Symptôme'), ('medication', 'Médicament'), ('side_effect', 'Effet secondaire'), ('mood', 'Humeur'), ('diet', 'Alimentation'), ('exercise', 'Exercice'), ('sleep', 'Sommeil'), ('general', 'Général')], default='general', max_length=30)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='health_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_health_notes',
                'ordering': ['-note_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', '-note_date'], name='personal_he_patient_3bd9ac_idx'), models.Index(fields=['category', '-note_date'], name='personal_he_categor_9a3448_idx')],
            },
        ),
        migrations.CreateModel(
            name='PreventiveCareReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True)),
                ('created_by_instance', models.UUIDField(blank=True, default=uuid.uuid4, help_text='UUID of instance that created this record')),
                ('modified_by_instance', models.UUIDField(blank=True, default=uuid.uuid4, help_text='UUID of instance that last modified this record')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('reminder_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('screening', 'Dépistage'), ('checkup', 'Bilan annuel'), ('dental', 'Contrôle dentaire'), ('eye_exam', 'Examen de la vue'), ('mammogram', 'Mammographie'), ('cervical_screening', 'Dépistage du cancer du col'), ('blood_pressure', 'Tension artérielle'), ('diabetes_screening', 'Dépistage du diabète'), ('malaria_prophylaxis', 'Prophylaxie antipaludique'), ('cholera_vaccination', 'Vaccination contre le choléra'), ('tb_screening', 'Dépistage de la tuberculose')], max_length=30)),
                ('due_date', models.DateField()),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('last_reminder_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='preventive_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'preventive_care_reminders',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['patient', 'due_date'], name='preventive__patient_fcb7a8_idx'), models.Index(fields=['is_completed', 'due_date'], name='preventive__is_comp_43c606_idx')],
            },
        ),
    ]
