# Generated by Django 6.0 on 2025-12-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_services_and_config'),
        ('appointments', '0002_initial'),
    ]

    operations = [
    ]
