# Generated by Django 6.0 on 2025-12-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_merge_20251208_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='created_by',
        ),
        migrations.RenameIndex(
            model_name='appointmentservice',
            new_name='appointment_appoint_04c069_idx',
            old_name='appointment_idx',
        ),
        migrations.RenameIndex(
            model_name='appointmentservice',
            new_name='appointment_service_32689b_idx',
            old_name='service_idx',
        ),
        migrations.DeleteModel(
            name='SystemConfiguration',
        ),
    ]
