# Generated by Django 6.0 on 2025-12-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_systemconfiguration_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='currency',
            field=models.CharField(default='EUR', help_text='Currency code for all fees', max_length=3),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultation_fee',
            field=models.IntegerField(default=0, help_text="Base consultation fee in patient's currency"),
        ),
    ]
