# Generated by Django 6.0 on 2025-12-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Base consultation fee in patient's currency", max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total after discounts', max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='consultation_fee + additional_services_total', max_digits=10),
        ),
    ]
