# Generated by Django 6.0 on 2025-12-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_doctor_alter_appointment_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointmentqueue',
            name='appointment_provide_932cb4_idx',
        ),
        migrations.RemoveIndex(
            model_name='availability',
            name='availabilit_provide_bcbbad_idx',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_uid',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_uid',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='appointmentqueue',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='provider',
        ),
    ]
