# Generated by Django 6.0 on 2025-12-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_remove_appointmentqueue_appointment_provide_932cb4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('cash', 'Cash'), ('onsite_cash', 'On-site Cash'), ('card', 'Card'), ('mobile_money', 'Mobile Money'), ('insurance', 'Insurance')], default='wallet', help_text='Payment method selected by patient', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment transaction reference number', max_length=100),
        ),
    ]
