# Generated by Django 6.0 on 2025-12-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_add_payment_method_to_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('onsite_cash', 'On-site Cash'), ('card', 'Card'), ('mobile_money', 'Mobile Money'), ('insurance', 'Insurance')], default='wallet', help_text='Payment method selected by patient', max_length=20),
        ),
    ]
