# Generated by Django 6.0 on 2025-12-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_appointment_created_by_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base consultation fee in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code for all fees', max_length=3),
        ),
    ]
