# Generated by Django 6.0 on 2025-12-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_standardize_to_usd_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base consultation fee in XOF', max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='currency',
            field=models.CharField(default='XOF', help_text='Currency code for all fees', max_length=3),
        ),
    ]
