# Generated by Django 6.0 on 2026-01-01 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_alter_appointment_appointment_type_and_more'),
        ('core', '0038_transaction_uid_alter_participantservice_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, db_column='service_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.participantservice', to_field='uid'),
        ),
    ]
