# Generated by Django 6.0 on 2026-01-02 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_appointment_uid_alter_appointment_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text="Heure d'enregistrement par QR code", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='substitute_doctor',
            field=models.ForeignKey(blank=True, help_text='Médecin remplaçant assigné', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='substitute_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='substitute_reason',
            field=models.CharField(blank=True, choices=[('absence', 'Absence'), ('congé', 'Congé'), ('urgence', 'Urgence'), ('surcharge', 'Surcharge de travail'), ('autre', 'Autre')], help_text='Raison du remplacement', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
    ]
