# Generated by Django 6.0 on 2025-12-07 00:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=20)),
                ('floor_number', models.CharField(max_length=10)),
                ('bed_type', models.CharField(choices=[('standard', 'Standard'), ('icu', 'Soins intensifs'), ('private', 'Privé'), ('semi_private', 'Semi-privé'), ('pediatric', 'Pédiatrique'), ('maternity', 'Maternité')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Occupé'), ('maintenance', 'En maintenance'), ('reserved', 'Réservé')], default='available', max_length=20)),
                ('has_oxygen', models.BooleanField(default=False)),
                ('has_monitor', models.BooleanField(default=False)),
                ('is_iBINTAtion', models.BooleanField(default=False)),
                ('last_cleaned', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='core.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_beds',
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('admission_type', models.CharField(choices=[('emergency', 'Urgence'), ('scheduled', 'Programmé'), ('outpatient', 'Ambulatoire'), ('observation', 'Observation')], default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('admitted', 'Admis'), ('discharged', 'Sorti'), ('transferred', 'Transféré'), ('deceased', 'Décédé')], default='pending', max_length=20)),
                ('chief_complaint', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('actual_discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('discharge_instructions', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('total_cost', models.IntegerField(default=0)),
                ('insurance_coverage', models.IntegerField(default=0)),
                ('patient_responsibility', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='core.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admissions', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='hospital.bed')),
            ],
            options={
                'db_table': 'hospital_admissions',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='HospitalBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('partially_paid', 'Partiellement payé'), ('paid', 'Payé'), ('overdue', 'En retard'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('total_amount', models.IntegerField(default=0)),
                ('discount_amount', models.IntegerField(default=0)),
                ('tax_amount', models.IntegerField(default=0)),
                ('insurance_coverage', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('balance_due', models.IntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('billing_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='hospital.admission')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_bills', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_hospital_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_bills',
                'ordering': ['-billing_date'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('consultation', 'Consultation'), ('procedure', 'Procédure'), ('medication', 'Médicament'), ('room_charge', 'Frais de chambre'), ('lab_test', 'Test laboratoire'), ('imaging', 'Imagerie'), ('surgery', 'Chirurgie'), ('equipment', 'Équipement'), ('other', 'Autre')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('date_of_service', models.DateField(default=django.utils.timezone.now)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hospital.hospitalbill')),
            ],
            options={
                'db_table': 'hospital_bill_items',
            },
        ),
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('administrator', 'Administrateur'), ('doctor', 'Médecin'), ('nurse', 'Infirmier(ère)'), ('surgeon', 'Chirurgien'), ('anesthesiologist', 'Anesthésiste'), ('radiologist', 'Radiologue'), ('lab_technician', 'Technicien de laboratoire'), ('pharmacist', 'Pharmacien'), ('receptionist', 'Réceptionniste'), ('janitor', "Agent d'entretien"), ('security', 'Sécurité'), ('it_staff', 'Personnel IT')], max_length=30)),
                ('employment_type', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('contract', 'Contractuel'), ('intern', 'Stagiaire')], default='full_time', max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_admit_patients', models.BooleanField(default=False)),
                ('can_discharge_patients', models.BooleanField(default=False)),
                ('can_prescribe', models.BooleanField(default=False)),
                ('can_perform_surgery', models.BooleanField(default=False)),
                ('can_manage_equipment', models.BooleanField(default=False)),
                ('can_manage_staff', models.BooleanField(default=False)),
                ('can_view_all_records', models.BooleanField(default=False)),
                ('shift_schedule', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='core.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_staff', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_employment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_staff',
            },
        ),
        migrations.CreateModel(
            name='DepartmentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.department')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='hospital.hospitalstaff')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='hospital.hospitalstaff')),
            ],
            options={
                'db_table': 'department_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='admitting_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to='hospital.hospitalstaff'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('insurance', 'Assurance'), ('check', 'Chèque')], max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hospital.hospitalbill')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='hospital.hospitalstaff')),
            ],
            options={
                'db_table': 'hospital_payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['hospital', 'status'], name='hospital_be_hospita_b6bd2a_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['department', 'status'], name='hospital_be_departm_3d0974_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('hospital', 'bed_number')},
        ),
        migrations.AddIndex(
            model_name='hospitalbill',
            index=models.Index(fields=['hospital', 'status'], name='hospital_bi_hospita_6ddc23_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalbill',
            index=models.Index(fields=['patient'], name='hospital_bi_patient_07fcd3_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalbill',
            index=models.Index(fields=['bill_number'], name='hospital_bi_bill_nu_6e413c_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalstaff',
            index=models.Index(fields=['hospital', 'is_active'], name='hospital_st_hospita_27cc4b_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalstaff',
            index=models.Index(fields=['department'], name='hospital_st_departm_66bfbd_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalstaff',
            index=models.Index(fields=['role'], name='hospital_st_role_224bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='departmenttask',
            index=models.Index(fields=['department', 'status'], name='department__departm_f0cbae_idx'),
        ),
        migrations.AddIndex(
            model_name='departmenttask',
            index=models.Index(fields=['assigned_to', 'status'], name='department__assigne_41ab44_idx'),
        ),
        migrations.AddIndex(
            model_name='departmenttask',
            index=models.Index(fields=['priority'], name='department__priorit_3e7e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['hospital', 'status'], name='hospital_ad_hospita_5e824e_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['patient'], name='hospital_ad_patient_69789d_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['admission_number'], name='hospital_ad_admissi_09eb07_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['admission_date'], name='hospital_ad_admissi_fcd20d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['hospital', 'payment_date'], name='hospital_pa_hospita_e6e3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bill'], name='hospital_pa_bill_id_7289e2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='hospital_pa_payment_84aff7_idx'),
        ),
    ]

