# Generated by Django 6.0 on 2025-12-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_bed_is_ibintation_bed_is_isolation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='is_iBINTAtion',
        ),
        migrations.AddField(
            model_name='bed',
            name='is_isolation',
            field=models.BooleanField(default=False),
        ),
    ]
