# Generated by Django 6.0 on 2025-12-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_set_default_hospital_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldata',
            name='consultation_fee',
            field=models.IntegerField(default=0),
        ),
    ]
