# Generated by Django 6.0 on 2025-12-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_hospitaldata_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Client-provided unique key to prevent duplicate admission creation', max_length=255, null=True, unique=True),
        ),
    ]
