# Generated by Django 6.0 on 2025-12-31 19:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_add_idempotency_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Global unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('version', models.IntegerField(default=1, help_text='Version number for conflict detection')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this record was last synced with cloud', null=True)),
                ('created_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that created this record', null=True)),
                ('modified_by_instance', models.UUIDField(blank=True, help_text='UUID of instance that last modified this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for sync purposes')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was marked as deleted', null=True)),
                ('region_code', models.CharField(db_index=True, default='global', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('imaging', 'Imagerie Médicale'), ('surgery', 'Chirurgie'), ('laboratory', 'Laboratoire'), ('emergency', 'Urgence'), ('consultation_specialist', 'Consultation Spécialiste'), ('hospitalization', 'Hospitalisation'), ('maternity', 'Maternité'), ('icu', 'Soins Intensifs'), ('physiotherapy', 'Physiothérapie'), ('dental', 'Dentaire'), ('optical', 'Optique'), ('other', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0, help_text='Price in XOF cents')),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_appointment', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(limit_choices_to={'role': 'hospital'}, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_services',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'is_active'], name='hospital_se_hospita_424a8f_idx'), models.Index(fields=['category', 'is_available'], name='hospital_se_categor_b6e95f_idx')],
            },
        ),
    ]
