# Generated by Django 6.0 on 2026-01-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_alter_admission_created_by_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldata',
            name='activation_code',
            field=models.CharField(blank=True, help_text='12-digit activation code for local instance', max_length=12),
        ),
        migrations.AddField(
            model_name='hospitaldata',
            name='identifier',
            field=models.CharField(blank=True, help_text='Human-readable unique identifier for subscription management', max_length=50, null=True, unique=True),
        ),
    ]
