# Generated by Django 6.0 on 2026-01-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_add_activation_code_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalstaff',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrateur'), ('doctor', 'Médecin'), ('nurse', 'Infirmier(ère)'), ('surgeon', 'Chirurgien'), ('anesthesiologist', 'Anesthésiste'), ('radiologist', 'Radiologue'), ('lab_technician', 'Technicien de laboratoire'), ('pharmacist', 'Pharmacien'), ('receptionist', 'Réceptionniste'), ('driver', 'Chauffeur'), ('janitor', "Agent d'entretien"), ('security', 'Sécurité'), ('it_staff', 'Personnel IT')], max_length=30),
        ),
    ]
