# Generated by Django 6.0 on 2025-12-23 13:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0004_alter_doctorservice_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAppointmentSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_specialty', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(choices=[('overdue_checkup', 'Overdue Checkup'), ('symptom_pattern', 'Symptom Pattern Detected'), ('preventive_care', 'Preventive Care'), ('follow_up', 'Follow-up Required'), ('medication_review', 'Medication Review'), ('health_risk', 'Health Risk Identified')], max_length=50)),
                ('explanation', models.TextField()),
                ('urgency', models.CharField(default='normal', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('suggested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('appointment_created', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_appointment_suggestions', to=settings.AUTH_USER_MODEL)),
                ('suggested_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctordata')),
            ],
            options={
                'db_table': 'ai_appointment_suggestions',
                'ordering': ['-suggested_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('escalated', 'Escalated to Human')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('escalated_to_staff', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(default=0.5, help_text='Sentiment analysis score 0-1')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('ai', 'AI Response'), ('system', 'System Message')], max_length=10)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Store intent, entities, confidence')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for review')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation')),
            ],
            options={
                'db_table': 'ai_chat_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AIHealthInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('recommendation', 'Recommendation'), ('warning', 'Warning'), ('trend', 'Trend'), ('prediction', 'Prediction'), ('analysis', 'Analysis')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('data_points_used', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence 0-1')),
                ('is_read', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_health_insights', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_insights', to='doctor.doctordata')),
            ],
            options={
                'db_table': 'ai_health_insights',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_type', models.CharField(choices=[('chat', 'Chat Assistant'), ('symptom_checker', 'Symptom Checker'), ('health_insight', 'Health Insight'), ('medication_reminder', 'Medication Reminder'), ('risk_assessment', 'Risk Assessment'), ('appointment_suggestion', 'Appointment Suggestion')], max_length=50)),
                ('feedback_type', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('inaccurate', 'Inaccurate'), ('inappropriate', 'Inappropriate')], max_length=20)),
                ('rating', models.IntegerField(blank=True, help_text='1-5 star rating', null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to=settings.AUTH_USER_MODEL)),
                ('related_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aiconversation')),
                ('related_insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aihealthinsight')),
            ],
            options={
                'db_table': 'ai_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIHealthRiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_category', models.CharField(choices=[('cardiovascular', 'Cardiovascular Disease'), ('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('obesity', 'Obesity'), ('mental_health', 'Mental Health'), ('general', 'General Health')], max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], max_length=20)),
                ('risk_score', models.FloatField(help_text='Numerical risk score 0-100')),
                ('risk_factors', models.JSONField(default=list, help_text='Contributing risk factors')),
                ('prevention_recommendations', models.TextField()),
                ('lifestyle_modifications', models.JSONField(default=list)),
                ('follow_up_actions', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_assessment_date', models.DateField(blank=True, null=True)),
                ('is_shared_with_doctor', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_risk_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_health_risk_assessments',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMedicationReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(help_text='e.g., twice daily, every 8 hours', max_length=100)),
                ('reminder_times', models.JSONField(default=list, help_text='List of reminder times')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('adherence_rate', models.FloatField(default=0.0, help_text='Percentage of doses taken on time')),
                ('last_taken_at', models.DateTimeField(blank=True, null=True)),
                ('missed_doses', models.IntegerField(default=0)),
                ('ai_insights', models.TextField(blank=True, help_text='AI-generated adherence insights')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_med_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_medication_reminders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISymptomChecker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms', models.JSONField(default=list, help_text='List of reported symptoms')),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Age, gender, medical history')),
                ('ai_analysis', models.TextField(blank=True)),
                ('possible_conditions', models.JSONField(blank=True, default=list)),
                ('urgency_level', models.CharField(blank=True, choices=[('low', 'Low - Self Care'), ('medium', 'Medium - See Doctor Soon'), ('high', 'High - See Doctor Today'), ('emergency', 'Emergency - Seek Immediate Care')], max_length=20)),
                ('recommendations', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('followed_up', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_symptom_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['participant', '-last_message_at'], name='ai_conversa_partici_65a627_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['status'], name='ai_conversa_status_02485a_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['conversation', 'timestamp'], name='ai_chat_mes_convers_bda5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='aihealthinsight',
            index=models.Index(fields=['patient', '-generated_at'], name='ai_health_i_patient_c23669_idx'),
        ),
        migrations.AddIndex(
            model_name='aihealthinsight',
            index=models.Index(fields=['priority', 'is_read'], name='ai_health_i_priorit_00965f_idx'),
        ),
    ]
