# Generated by Django 6.0 on 2025-12-25 12:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aimodelperformance_aiconsolidatedhealthreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('chat', 'Chat Assistant'), ('health_insights', 'Health Insights'), ('symptom_checker', 'Symptom Checker'), ('medication_reminder', 'Medication Reminder'), ('risk_assessment', 'Risk Assessment'), ('hr_analytics', 'HR Analytics'), ('financial_analytics', 'Financial Analytics'), ('diagnostic_analysis', 'Diagnostic Analysis')], max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('patient_flow', 'Patient Flow'), ('resource_utilization', 'Resource Utilization'), ('revenue_optimization', 'Revenue Optimization'), ('quality_metrics', 'Quality Metrics'), ('hr_analytics', 'HR Analytics'), ('financial_analytics', 'Financial Analytics')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('insight_text', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('metric_name', models.CharField(blank=True, max_length=100)),
                ('metric_value', models.CharField(blank=True, max_length=100)),
                ('trend', models.CharField(blank=True, max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aimodelperformance',
            index=models.Index(fields=['is_active', '-last_evaluation_date'], name='ai_model_pe_is_acti_dba009_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodelperformance',
            index=models.Index(fields=['model_type'], name='ai_model_pe_model_t_dfbcd7_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeature',
            index=models.Index(fields=['type', 'is_active'], name='ai_features_type_ab75df_idx'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['organization', '-created_at'], name='ai_insights_organiz_722de7_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['category', 'priority'], name='ai_insights_categor_adaf63_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['is_dismissed'], name='ai_insights_is_dism_5f5d43_idx'),
        ),
    ]
