# Generated by Django 6.0 on 2025-12-25 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aifeature_aiinsight_and_more'),
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aiappointmentsuggestion',
            index=models.Index(fields=['patient', '-suggested_at'], name='ai_appointm_patient_87c521_idx'),
        ),
        migrations.AddIndex(
            model_name='aiappointmentsuggestion',
            index=models.Index(fields=['is_dismissed', 'is_accepted'], name='ai_appointm_is_dism_dc4559_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['feature_type', '-created_at'], name='ai_feedback_feature_70dcdf_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['feedback_type', 'rating'], name='ai_feedback_feedbac_d58ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='aihealthriskassessment',
            index=models.Index(fields=['patient', '-assessed_at'], name='ai_health_r_patient_bcc5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='aihealthriskassessment',
            index=models.Index(fields=['risk_level', 'risk_category'], name='ai_health_r_risk_le_29171b_idx'),
        ),
        migrations.AddIndex(
            model_name='aimedicationreminder',
            index=models.Index(fields=['patient', 'is_active'], name='ai_medicati_patient_7f7a16_idx'),
        ),
        migrations.AddIndex(
            model_name='aimedicationreminder',
            index=models.Index(fields=['-start_date'], name='ai_medicati_start_d_872f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='aisymptomchecker',
            index=models.Index(fields=['patient', '-created_at'], name='ai_symptom__patient_7e16a6_idx'),
        ),
        migrations.AddIndex(
            model_name='aisymptomchecker',
            index=models.Index(fields=['urgency_level'], name='ai_symptom__urgency_463866_idx'),
        ),
    ]
