# Generated by Django 6.0 on 2025-12-07 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('general_practice', 'General Practice'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('orthopedics', 'Orthopedics'), ('neurology', 'Neurology'), ('oncology', 'Oncology')], max_length=100)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('qualifications', models.JSONField(default=list)),
                ('consultation_fee', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('languages_spoken', models.JSONField(default=list)),
                ('rating', models.FloatField(default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_consultations', models.IntegerField(default=0)),
                ('is_available_for_telemedicine', models.BooleanField(default=False)),
                ('affiliated_hospitals', models.JSONField(blank=True, default=list)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_data',
            },
        ),
    ]
