# Generated by Django 6.0 on 2025-12-10 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('consultation', 'Consultation'), ('diagnostic', 'Examen Diagnostique'), ('therapy', 'Thérapie'), ('vaccination', 'Vaccination'), ('other', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('XOF', 'XOF'), ('EUR', 'EUR'), ('USD', 'USD')], default='XOF', max_length=3)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_services',
                'ordering': ['-created_at'],
            },
        ),
    ]
