# Generated by Django 6.0 on 2025-12-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_add_doctor_affiliation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorservice',
            name='currency',
            field=models.CharField(choices=[('FCFA', 'FCFA'), ('XOF', 'XOF'), ('EUR', 'EUR'), ('USD', 'USD')], default='FCFA', max_length=10),
        ),
    ]
