# Generated by Django 6.0 on 2025-12-14 10:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_migrate_services_to_participant_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAffiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('affiliation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_affiliations', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(limit_choices_to={'role': 'hospital'}, on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_affiliations',
                'indexes': [models.Index(fields=['doctor', 'is_active'], name='doctor_affi_doctor__3ca459_idx'), models.Index(fields=['hospital', 'is_active'], name='doctor_affi_hospita_730b81_idx')],
                'unique_together': {('doctor', 'hospital')},
            },
        ),
    ]
