# Generated by Django 6.0 on 2025-12-10 10:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('service_types', models.JSONField(default=list)),
                ('coverage_areas', models.JSONField(default=list)),
                ('operating_hours', models.JSONField(default=dict)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('rating', models.FloatField(default=0.0)),
                ('total_trips', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transport_providers',
                'indexes': [models.Index(fields=['status'], name='transport_p_status_84f75f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('transport_type', models.CharField(choices=[('ambulance', 'Ambulance'), ('medical_taxi', 'Medical Taxi'), ('wheelchair_transport', 'Wheelchair Transport'), ('stretcher_transport', 'Stretcher Transport'), ('regular_taxi', 'Regular Taxi')], max_length=50)),
                ('urgency', models.CharField(choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('scheduled', 'Scheduled'), ('routine', 'Routine')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('driver_assigned', 'Driver Assigned'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('dropoff_address', models.TextField()),
                ('dropoff_latitude', models.FloatField(blank=True, null=True)),
                ('dropoff_longitude', models.FloatField(blank=True, null=True)),
                ('scheduled_pickup_time', models.DateTimeField()),
                ('actual_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('actual_dropoff_time', models.DateTimeField(blank=True, null=True)),
                ('driver_id', models.UUIDField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=255)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_id', models.UUIDField(blank=True, null=True)),
                ('patient_notes', models.TextField(blank=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('medical_equipment_needed', models.JSONField(blank=True, default=list)),
                ('companion_count', models.IntegerField(default=0)),
                ('companion_names', models.JSONField(blank=True, default=list)),
                ('estimated_distance', models.FloatField(blank=True, null=True)),
                ('estimated_duration', models.IntegerField(blank=True, null=True)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transport_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='transport_r_patient_fc6d42_idx'), models.Index(fields=['request_number'], name='transport_r_request_cb1e85_idx'), models.Index(fields=['scheduled_pickup_time'], name='transport_r_schedul_cecd2e_idx'), models.Index(fields=['status'], name='transport_r_status_032a66_idx')],
            },
        ),
    ]
