# Generated by Django 6.0 on 2025-12-25 16:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideShareProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('uber', 'Uber'), ('gozem', 'Gozem'), ('bolt', 'Bolt'), ('yango', 'Yango'), ('internal', 'BINTACURA Internal')], max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('webhook_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_types_available', models.JSONField(default=list)),
                ('coverage_areas', models.JSONField(default=list)),
                ('average_response_time', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_trips', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rideshare_providers',
                'indexes': [models.Index(fields=['name', 'is_active'], name='rideshare_p_name_f48a54_idx')],
            },
        ),
        migrations.CreateModel(
            name='RideShareQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort'), ('xl', 'XL'), ('van', 'Van'), ('ambulance', 'Ambulance'), ('medical_van', 'Medical Van')], max_length=50)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surge_multiplier', models.FloatField(default=1.0)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('driver_name', models.CharField(blank=True, max_length=255)),
                ('driver_photo_url', models.URLField(blank=True)),
                ('driver_rating', models.FloatField(blank=True, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('driver_latitude', models.FloatField(blank=True, null=True)),
                ('driver_longitude', models.FloatField(blank=True, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_color', models.CharField(blank=True, max_length=50)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20)),
                ('vehicle_capacity', models.IntegerField(default=4)),
                ('estimated_arrival_minutes', models.IntegerField()),
                ('estimated_trip_duration_minutes', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('provider_quote_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='transport.rideshareprovider')),
                ('transport_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='transport.transportrequest')),
            ],
            options={
                'db_table': 'rideshare_quotes',
                'ordering': ['total_fare'],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('heading', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('distance_to_pickup', models.FloatField(blank=True, null=True)),
                ('distance_to_dropoff', models.FloatField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('transport_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_locations', to='transport.transportrequest')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_locations', to='transport.ridesharequote')),
            ],
            options={
                'db_table': 'driver_locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransportChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('patient', 'Patient'), ('driver', 'Driver'), ('system', 'System')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('location', 'Location'), ('image', 'Image'), ('system', 'System')], default='text', max_length=20)),
                ('message', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='transport.ridesharequote')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_messages', to=settings.AUTH_USER_MODEL)),
                ('transport_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='transport.transportrequest')),
            ],
            options={
                'db_table': 'transport_chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalTransportNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('can_provide_transport', models.BooleanField(default=False)),
                ('estimated_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('proposed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_notifications', to=settings.AUTH_USER_MODEL)),
                ('transport_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_notifications', to='transport.transportrequest')),
            ],
            options={
                'db_table': 'hospital_transport_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'status'], name='hospital_tr_hospita_1a00c4_idx'), models.Index(fields=['transport_request'], name='hospital_tr_transpo_6ab755_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ridesharequote',
            index=models.Index(fields=['transport_request', 'status'], name='rideshare_q_transpo_cd1690_idx'),
        ),
        migrations.AddIndex(
            model_name='ridesharequote',
            index=models.Index(fields=['expires_at'], name='rideshare_q_expires_cd1330_idx'),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['transport_request', '-timestamp'], name='driver_loca_transpo_dfc4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['quote', '-timestamp'], name='driver_loca_quote_i_393783_idx'),
        ),
        migrations.AddIndex(
            model_name='transportchat',
            index=models.Index(fields=['transport_request', 'created_at'], name='transport_c_transpo_8482f5_idx'),
        ),
        migrations.AddIndex(
            model_name='transportchat',
            index=models.Index(fields=['sender', 'is_read'], name='transport_c_sender__33daa8_idx'),
        ),
    ]

