# Generated by Django 6.0 on 2025-12-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_driverlocation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharequote',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
