# Generated by Django 6.0 on 2025-12-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_standardize_to_usd_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharequote',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
    ]
