# Generated by Django 6.0 on 2026-01-03 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_add_syncmixin_to_transportprovider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='assigned_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
