# Generated by Django 6.0 on 2026-01-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_transportrequest_assigned_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the request was accepted by a hospital', null=True),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='transfer_history',
            field=models.JSONField(blank=True, default=list, help_text='History of transfers between hospitals'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('driver_assigned', 'Driver Assigned'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
